import type { CareerInterest } from "./personalization/types";

export type CareerPathMilestone = {
  id: string;
  title: string;
  description: string;
};

export type CareerPath = {
  id: string;
  title: string;
  category: string;
  description: string;
  entryRoles: string[];
  targetRoles: string[];
  relatedSkills: Array<"health" | "wealth" | "career" | "family" | "mindset">;
  careerInterests: CareerInterest[];
  recommendedCertificationIds: string[];
  recommendedSideHustleIds: string[];
  milestones: CareerPathMilestone[];
  difficulty: "starter" | "intermediate" | "advanced";
  typicalDirection: string;
  disclaimer?: string;
};

function ms(prefix: string, titles: string[]): CareerPathMilestone[] {
  return titles.map((title, i) => ({
    id: `${prefix}-${i + 1}`,
    title,
    description: title,
  }));
}

/** Starter library — practical paths, no salary/outcome guarantees. */
export const CAREER_PATHS: CareerPath[] = [
  {
    id: "maint-tech-to-supervisor",
    title: "Maintenance Technician → Supervisor",
    category: "Facilities",
    description: "Build technical reliability, then add leadership, planning, and vendor communication.",
    entryRoles: ["Maintenance Technician", "Maintenance Helper", "Facilities Tech"],
    targetRoles: ["Maintenance Supervisor", "Lead Technician"],
    relatedSkills: ["career", "mindset", "wealth"],
    careerInterests: ["maintenance", "trades", "management"],
    recommendedCertificationIds: ["osha-10", "epa-608"],
    recommendedSideHustleIds: ["handyman-services", "junk-removal"],
    milestones: ms("mts", [
      "Document recurring repairs and preventive routines",
      "Complete technical consistency quests for 2 weeks",
      "Lead one small project or shutdown checklist",
      "Practice vendor/budget notes",
      "Ask for lead or acting-supervisor opportunities",
    ]),
    difficulty: "intermediate",
    typicalDirection: "Operations leadership in facilities",
  },
  {
    id: "supervisor-to-facilities-mgr",
    title: "Maintenance Supervisor → Facilities Manager",
    category: "Facilities",
    description: "Expand from crew leadership into budgeting, compliance, and multi-site planning.",
    entryRoles: ["Maintenance Supervisor", "Lead Technician"],
    targetRoles: ["Facilities Manager", "Facilities Coordinator"],
    relatedSkills: ["career", "wealth", "mindset"],
    careerInterests: ["maintenance", "management", "business"],
    recommendedCertificationIds: ["pmp-google", "osha-30"],
    recommendedSideHustleIds: ["property-support"],
    milestones: ms("fm", [
      "Own a budget line or parts inventory process",
      "Build a preventive maintenance calendar",
      "Complete leadership and planning quests",
      "Shadow facilities planning meetings",
      "Prepare a role-ready resume packet",
    ]),
    difficulty: "advanced",
    typicalDirection: "Facilities / operations management",
  },
  {
    id: "food-to-shift-lead",
    title: "Food Service Worker → Shift Lead",
    category: "Hospitality",
    description: "Move from task excellence to running a shift: pacing, coaching, and service recovery.",
    entryRoles: ["Crew Member", "Line Cook", "Cashier", "Server"],
    targetRoles: ["Shift Lead", "Shift Supervisor"],
    relatedSkills: ["career", "family", "mindset"],
    careerInterests: ["hospitality", "management"],
    recommendedCertificationIds: ["servsafe", "cpr-first-aid"],
    recommendedSideHustleIds: ["meal-prep", "event-help"],
    milestones: ms("fsl", [
      "Master one station end-to-end",
      "Learn opening/closing checklists",
      "Coach a teammate through a task",
      "Handle a service recovery calmly",
      "Ask to train as shift lead",
    ]),
    difficulty: "starter",
    typicalDirection: "Hospitality supervision",
  },
  {
    id: "shift-lead-to-fsm",
    title: "Shift Lead → Food Service Manager",
    category: "Hospitality",
    description: "Add scheduling, inventory, and guest experience ownership.",
    entryRoles: ["Shift Lead", "Assistant Manager"],
    targetRoles: ["Food Service Manager", "Restaurant Manager"],
    relatedSkills: ["career", "wealth", "mindset"],
    careerInterests: ["hospitality", "management", "business"],
    recommendedCertificationIds: ["servsafe", "google-pm"],
    recommendedSideHustleIds: ["catering-assistant"],
    milestones: ms("fsm", [
      "Own a weekly schedule draft",
      "Run inventory count accurately",
      "Improve one guest-experience metric",
      "Complete career leadership quests",
      "Prepare manager interview stories",
    ]),
    difficulty: "intermediate",
    typicalDirection: "Restaurant / food ops management",
  },
  {
    id: "fsm-to-gm",
    title: "Food Service Manager → General Manager",
    category: "Hospitality",
    description: "Scale from one unit’s operations to P&L awareness and multi-team leadership.",
    entryRoles: ["Food Service Manager", "Restaurant Manager"],
    targetRoles: ["General Manager", "Area Manager"],
    relatedSkills: ["career", "wealth", "mindset"],
    careerInterests: ["hospitality", "management", "business"],
    recommendedCertificationIds: ["google-pm", "hubspot-inbound"],
    recommendedSideHustleIds: [],
    milestones: ms("gm", [
      "Learn weekly sales and labor basics",
      "Lead a hiring or training improvement",
      "Own a cost-control experiment",
      "Build a 90-day operating plan draft",
      "Network with multi-unit leaders",
    ]),
    difficulty: "advanced",
    typicalDirection: "Multi-unit hospitality leadership",
  },
  {
    id: "entry-it-helpdesk",
    title: "Entry-Level IT → Help Desk",
    category: "Technology",
    description: "Build troubleshooting fundamentals and customer communication for support roles.",
    entryRoles: ["IT Intern", "Retail Tech Support", "Career Changer"],
    targetRoles: ["Help Desk Technician", "IT Support Specialist"],
    relatedSkills: ["career", "mindset"],
    careerInterests: ["technology"],
    recommendedCertificationIds: ["google-it-support", "comptia-a-plus"],
    recommendedSideHustleIds: ["tech-tutoring", "device-setup"],
    milestones: ms("hd", [
      "Complete a foundational IT cert path",
      "Practice ticket-style troubleshooting notes",
      "Build a home lab or portfolio of fixes",
      "Finish career quests on communication",
      "Apply to help desk roles with proof of practice",
    ]),
    difficulty: "starter",
    typicalDirection: "IT support",
  },
  {
    id: "helpdesk-to-sysadmin",
    title: "Help Desk → System Administrator",
    category: "Technology",
    description: "Move from tickets to systems: scripting, identity, and reliability.",
    entryRoles: ["Help Desk Technician", "IT Support"],
    targetRoles: ["System Administrator", "Junior SysAdmin"],
    relatedSkills: ["career", "mindset", "wealth"],
    careerInterests: ["technology"],
    recommendedCertificationIds: ["comptia-network", "microsoft-az900"],
    recommendedSideHustleIds: ["freelance-it"],
    milestones: ms("sa", [
      "Automate one repetitive support task",
      "Learn basic networking and identity concepts",
      "Document a small infrastructure change",
      "Earn a networking or cloud fundamentals credential",
      "Seek stretch projects on servers/cloud",
    ]),
    difficulty: "intermediate",
    typicalDirection: "Infrastructure / systems",
  },
  {
    id: "sysadmin-to-security",
    title: "System Administrator → Cybersecurity",
    category: "Technology",
    description: "Layer security fundamentals onto systems experience.",
    entryRoles: ["System Administrator", "Network Admin"],
    targetRoles: ["Security Analyst", "SOC Analyst"],
    relatedSkills: ["career", "mindset"],
    careerInterests: ["technology"],
    recommendedCertificationIds: ["isc2-cc", "comptia-security"],
    recommendedSideHustleIds: [],
    milestones: ms("sec", [
      "Study security fundamentals (CC or Security+ path)",
      "Practice log review / incident write-ups",
      "Harden one system with a checklist",
      "Complete mindset focus quests for deep work",
      "Target analyst roles with a security portfolio",
    ]),
    difficulty: "advanced",
    typicalDirection: "Cybersecurity operations",
    disclaimer: "Some security roles require background checks or additional employer requirements.",
  },
  {
    id: "sales-assoc-to-manager",
    title: "Sales Associate → Sales Manager",
    category: "Sales",
    description: "Grow from individual selling to coaching a team and owning a pipeline.",
    entryRoles: ["Sales Associate", "Retail Associate"],
    targetRoles: ["Sales Manager", "Sales Lead"],
    relatedSkills: ["career", "wealth", "family"],
    careerInterests: ["sales", "management"],
    recommendedCertificationIds: ["hubspot-inbound", "google-digital-marketing"],
    recommendedSideHustleIds: ["affiliate-content"],
    milestones: ms("sm", [
      "Hit a consistent personal sales cadence",
      "Document winning talk tracks",
      "Mentor a newer associate",
      "Learn basic pipeline reporting",
      "Ask for lead/manager shadowing",
    ]),
    difficulty: "intermediate",
    typicalDirection: "Sales leadership",
  },
  {
    id: "cs-to-team-lead",
    title: "Customer Service → Team Lead",
    category: "Operations",
    description: "Turn service excellence into coaching, quality, and escalation handling.",
    entryRoles: ["Customer Service Rep", "Support Agent"],
    targetRoles: ["Team Lead", "Support Lead"],
    relatedSkills: ["career", "family", "mindset"],
    careerInterests: ["management", "sales", "business"],
    recommendedCertificationIds: ["google-pm", "hubspot-inbound"],
    recommendedSideHustleIds: ["virtual-assistant"],
    milestones: ms("cstl", [
      "Maintain strong quality scores",
      "Handle escalations with calm notes",
      "Peer-coach one teammate",
      "Learn workforce basics (breaks, coverage)",
      "Apply for lead openings with examples",
    ]),
    difficulty: "starter",
    typicalDirection: "Support leadership",
  },
  {
    id: "admin-to-office-mgr",
    title: "Administrative Assistant → Office Manager",
    category: "Business",
    description: "Expand coordination work into vendor, calendar, and process ownership.",
    entryRoles: ["Administrative Assistant", "Office Coordinator"],
    targetRoles: ["Office Manager", "Operations Coordinator"],
    relatedSkills: ["career", "wealth", "mindset"],
    careerInterests: ["business", "management"],
    recommendedCertificationIds: ["google-pm", "quickbooks"],
    recommendedSideHustleIds: ["virtual-assistant", "bookkeeping-basic"],
    milestones: ms("om", [
      "Own a recurring operations checklist",
      "Improve one filing or scheduling system",
      "Track a small budget or supply spend",
      "Complete career organization quests",
      "Propose an office-manager scope expansion",
    ]),
    difficulty: "intermediate",
    typicalDirection: "Business operations",
  },
  {
    id: "warehouse-to-ops-supervisor",
    title: "Warehouse Associate → Operations Supervisor",
    category: "Operations",
    description: "Pair floor excellence with safety, throughput, and people leadership.",
    entryRoles: ["Warehouse Associate", "Picker/Packer"],
    targetRoles: ["Operations Supervisor", "Warehouse Lead"],
    relatedSkills: ["career", "health", "mindset"],
    careerInterests: ["management", "trades", "business"],
    recommendedCertificationIds: ["osha-10", "google-pm"],
    recommendedSideHustleIds: ["junk-removal"],
    milestones: ms("ops", [
      "Master safety and quality standards",
      "Learn shift throughput basics",
      "Lead a 5S or cleanup improvement",
      "Coach a new hire through SOPs",
      "Apply for lead/supervisor roles",
    ]),
    difficulty: "intermediate",
    typicalDirection: "Logistics supervision",
  },
  {
    id: "healthcare-support-to-admin",
    title: "Healthcare Support → Healthcare Administration",
    category: "Healthcare",
    description: "Bridge patient-facing support with scheduling, compliance, and admin systems.",
    entryRoles: ["Medical Assistant", "Patient Support", "Front Desk"],
    targetRoles: ["Healthcare Administrator", "Clinic Coordinator"],
    relatedSkills: ["career", "family", "mindset"],
    careerInterests: ["healthcare", "management", "business"],
    recommendedCertificationIds: ["cpr-first-aid", "google-pm"],
    recommendedSideHustleIds: [],
    milestones: ms("hca", [
      "Learn clinic workflow end-to-end",
      "Improve a scheduling or intake step",
      "Study privacy/compliance basics with employer guidance",
      "Complete communication quests",
      "Target coordinator openings",
    ]),
    difficulty: "intermediate",
    typicalDirection: "Clinic / healthcare ops",
    disclaimer: "Licensed clinical roles require verified credentials — always check local requirements.",
  },
  {
    id: "trade-apprentice-journeyman",
    title: "Skilled Trade Apprentice → Journeyman Pathway",
    category: "Trades",
    description: "Structure apprenticeship hours, skill proofs, and exam readiness.",
    entryRoles: ["Apprentice", "Helper", "Trainee"],
    targetRoles: ["Journeyman", "Licensed Tradesperson"],
    relatedSkills: ["career", "wealth", "health"],
    careerInterests: ["trades", "maintenance"],
    recommendedCertificationIds: ["osha-10", "epa-608"],
    recommendedSideHustleIds: ["handyman-services"],
    milestones: ms("trd", [
      "Track hours and skill checklists",
      "Master tool safety and jobsite habits",
      "Complete technical practice quests",
      "Prepare for required exams with official materials",
      "Build a work-quality portfolio (photos/notes)",
    ]),
    difficulty: "advanced",
    typicalDirection: "Licensed trades",
    disclaimer: "Licensing and apprenticeship rules vary by location — verify with your state/local board.",
  },
  {
    id: "coord-to-pm",
    title: "Project Coordinator → Project Manager",
    category: "Business",
    description: "Grow from tracking tasks to owning scope, timeline, and stakeholder updates.",
    entryRoles: ["Project Coordinator", "Operations Coordinator"],
    targetRoles: ["Project Manager", "Junior PM"],
    relatedSkills: ["career", "mindset", "wealth"],
    careerInterests: ["management", "business", "technology"],
    recommendedCertificationIds: ["google-pm", "pmp-capm"],
    recommendedSideHustleIds: ["freelance-pm"],
    milestones: ms("pm", [
      "Own a RAID/risk log for one project",
      "Run a standup or status meeting",
      "Complete a PM fundamentals credential",
      "Deliver a retrospective write-up",
      "Apply for PM roles with case examples",
    ]),
    difficulty: "intermediate",
    typicalDirection: "Project delivery leadership",
  },
  {
    id: "freelancer-to-agency",
    title: "Freelancer → Agency Owner",
    category: "Entrepreneurship",
    description: "Productize services, add systems, then optionally hire or partner.",
    entryRoles: ["Freelancer", "Independent Contractor"],
    targetRoles: ["Agency Owner", "Studio Owner"],
    relatedSkills: ["wealth", "career", "mindset"],
    careerInterests: ["entrepreneurship", "business", "sales"],
    recommendedCertificationIds: ["hubspot-inbound", "google-digital-marketing"],
    recommendedSideHustleIds: ["freelance-writing", "web-services"],
    milestones: ms("agy", [
      "Define a niche offer and pricing sheet",
      "Land repeatable client delivery SOPs",
      "Track profit after tools and taxes",
      "Build a simple pipeline habit",
      "Decide hire vs stay solo with clear math",
    ]),
    difficulty: "advanced",
    typicalDirection: "Service business ownership",
  },
  {
    id: "reseller-to-ecommerce",
    title: "Reseller → E-commerce Business Owner",
    category: "Entrepreneurship",
    description: "Systematize sourcing, listings, and customer ops into a real store operation.",
    entryRoles: ["Reseller", "Flipper"],
    targetRoles: ["E-commerce Owner", "Store Operator"],
    relatedSkills: ["wealth", "career", "mindset"],
    careerInterests: ["entrepreneurship", "business", "sales"],
    recommendedCertificationIds: ["google-digital-marketing", "google-analytics"],
    recommendedSideHustleIds: ["thrift-reselling", "print-on-demand"],
    milestones: ms("ecom", [
      "Pick a niche and brand basics",
      "Standardize listing quality",
      "Track margins after fees/shipping",
      "Add one marketing channel deliberately",
      "Set weekly ops cadence (orders, returns, restock)",
    ]),
    difficulty: "intermediate",
    typicalDirection: "Online retail business",
  },
  {
    id: "side-hustle-to-small-biz",
    title: "Side Hustler → Small Business Owner",
    category: "Entrepreneurship",
    description: "Validate demand, formalize basics, and decide when to scale hours.",
    entryRoles: ["Side Hustler", "Gig Worker"],
    targetRoles: ["Small Business Owner"],
    relatedSkills: ["wealth", "career", "mindset"],
    careerInterests: ["entrepreneurship", "business"],
    recommendedCertificationIds: ["quickbooks", "hubspot-inbound"],
    recommendedSideHustleIds: ["thrift-reselling", "handyman-services", "virtual-assistant"],
    milestones: ms("smb", [
      "Validate repeat paying customers",
      "Separate personal and business money tracking",
      "Write a simple offer + fulfillment checklist",
      "Complete wealth and career quests weekly",
      "Set a go/no-go scale decision date",
    ]),
    difficulty: "intermediate",
    typicalDirection: "Owner-operated business",
  },
  {
    id: "retail-to-asm",
    title: "Retail Associate → Assistant Store Manager",
    category: "Retail",
    description: "Combine sales floor excellence with merchandising and shift leadership.",
    entryRoles: ["Retail Associate", "Cashier"],
    targetRoles: ["Assistant Store Manager", "Key Holder"],
    relatedSkills: ["career", "wealth", "family"],
    careerInterests: ["management", "sales", "business"],
    recommendedCertificationIds: ["google-pm", "cpr-first-aid"],
    recommendedSideHustleIds: [],
    milestones: ms("asm", [
      "Learn open/close procedures",
      "Own a merchandising zone",
      "Coach associates on service standards",
      "Practice inventory accuracy",
      "Apply for key-holder / ASM roles",
    ]),
    difficulty: "starter",
    typicalDirection: "Retail management",
  },
  {
    id: "driver-to-fleet-lead",
    title: "Delivery Driver → Fleet / Route Lead",
    category: "Logistics",
    description: "Add route planning, safety coaching, and dispatch coordination.",
    entryRoles: ["Delivery Driver", "Courier"],
    targetRoles: ["Route Lead", "Fleet Coordinator"],
    relatedSkills: ["career", "health", "mindset"],
    careerInterests: ["management", "trades", "business"],
    recommendedCertificationIds: ["osha-10", "cpr-first-aid"],
    recommendedSideHustleIds: ["junk-removal"],
    milestones: ms("flt", [
      "Maintain clean safety and on-time record",
      "Learn route optimization basics",
      "Help onboard a new driver",
      "Complete health stamina quests",
      "Ask for lead/dispatch stretch work",
    ]),
    difficulty: "intermediate",
    typicalDirection: "Fleet operations",
    disclaimer: "Commercial driving credentials (e.g., CDL) may be required for some roles — verify requirements.",
  },
  {
    id: "creator-to-content-lead",
    title: "Creator → Content Lead",
    category: "Creative",
    description: "Turn consistent creating into editorial planning and brand systems.",
    entryRoles: ["Content Creator", "Social Media Freelancer"],
    targetRoles: ["Content Lead", "Social Media Manager"],
    relatedSkills: ["career", "mindset", "wealth"],
    careerInterests: ["sales", "entrepreneurship", "business"],
    recommendedCertificationIds: ["google-digital-marketing", "hubspot-content"],
    recommendedSideHustleIds: ["affiliate-content", "freelance-writing"],
    milestones: ms("cnt", [
      "Publish on a reliable cadence",
      "Build a simple content calendar",
      "Measure what converts (not only vanity metrics)",
      "Productize one service offer",
      "Pitch lead/manager scope with portfolio",
    ]),
    difficulty: "intermediate",
    typicalDirection: "Content / brand operations",
  },
  {
    id: "analyst-track",
    title: "Operations Analyst Pathway",
    category: "Business",
    description: "Use data hygiene, dashboards, and process thinking to support decisions.",
    entryRoles: ["Coordinator", "Specialist", "Career Changer"],
    targetRoles: ["Operations Analyst", "Business Analyst"],
    relatedSkills: ["career", "mindset", "wealth"],
    careerInterests: ["business", "technology", "management"],
    recommendedCertificationIds: ["google-data-analytics", "google-analytics"],
    recommendedSideHustleIds: ["freelance-pm"],
    milestones: ms("an", [
      "Clean one messy spreadsheet into a reliable source",
      "Build a simple dashboard for a real process",
      "Complete an analytics fundamentals path",
      "Write a one-page insight memo",
      "Target analyst roles with portfolio samples",
    ]),
    difficulty: "intermediate",
    typicalDirection: "Analytics-enabled operations",
  },
  {
    id: "hr-coordinator-path",
    title: "People Ops / HR Coordinator Pathway",
    category: "Business",
    description: "Focus on hiring logistics, onboarding quality, and employee support systems.",
    entryRoles: ["Office Coordinator", "Recruiter Assistant"],
    targetRoles: ["HR Coordinator", "People Operations Coordinator"],
    relatedSkills: ["career", "family", "mindset"],
    careerInterests: ["management", "business", "healthcare"],
    recommendedCertificationIds: ["google-pm", "hubspot-inbound"],
    recommendedSideHustleIds: ["virtual-assistant"],
    milestones: ms("hr", [
      "Improve an onboarding checklist",
      "Learn confidential handling norms",
      "Support one hiring pipeline end-to-end",
      "Complete communication quests",
      "Apply to coordinator roles with examples",
    ]),
    difficulty: "intermediate",
    typicalDirection: "People operations",
  },
  {
    id: "nurse-adjacent-admin",
    title: "Clinical Support → Care Coordination",
    category: "Healthcare",
    description: "Combine patient empathy with scheduling and cross-team coordination.",
    entryRoles: ["CNA", "Medical Assistant", "Patient Advocate"],
    targetRoles: ["Care Coordinator", "Patient Care Coordinator"],
    relatedSkills: ["family", "career", "mindset"],
    careerInterests: ["healthcare", "management"],
    recommendedCertificationIds: ["cpr-first-aid"],
    recommendedSideHustleIds: [],
    milestones: ms("cc", [
      "Map patient journey touchpoints",
      "Practice clear handoff notes",
      "Improve one scheduling friction point",
      "Complete family/communication quests",
      "Target coordinator openings with supervisor guidance",
    ]),
    difficulty: "intermediate",
    typicalDirection: "Care coordination",
    disclaimer: "Clinical scope of practice is regulated — follow employer and licensing rules.",
  },
  {
    id: "marketing-assoc-to-manager",
    title: "Marketing Associate → Marketing Manager",
    category: "Marketing",
    description: "Move from campaign execution to channel ownership and measurement.",
    entryRoles: ["Marketing Associate", "Coordinator"],
    targetRoles: ["Marketing Manager", "Growth Lead"],
    relatedSkills: ["career", "wealth", "mindset"],
    careerInterests: ["sales", "business", "entrepreneurship"],
    recommendedCertificationIds: ["google-digital-marketing", "hubspot-inbound", "google-ads"],
    recommendedSideHustleIds: ["affiliate-content"],
    milestones: ms("mkt", [
      "Own one channel end-to-end",
      "Ship experiments with clear hypotheses",
      "Earn a marketing fundamentals credential",
      "Build a simple performance report",
      "Lead a small campaign retrospective",
    ]),
    difficulty: "intermediate",
    typicalDirection: "Marketing leadership",
  },
  {
    id: "teacher-adj-corporate-training",
    title: "Instructor / Trainer → Corporate Learning",
    category: "Education",
    description: "Translate teaching skills into workplace learning design and facilitation.",
    entryRoles: ["Teacher", "Trainer", "Tutor"],
    targetRoles: ["Corporate Trainer", "L&D Specialist"],
    relatedSkills: ["career", "mindset", "family"],
    careerInterests: ["management", "business", "healthcare"],
    recommendedCertificationIds: ["google-pm"],
    recommendedSideHustleIds: ["tech-tutoring"],
    milestones: ms("ld", [
      "Design one short workshop with outcomes",
      "Collect feedback and iterate",
      "Build a sample curriculum outline",
      "Complete communication and mindset quests",
      "Target L&D / trainer roles with portfolio",
    ]),
    difficulty: "intermediate",
    typicalDirection: "Learning & development",
  },
  {
    id: "finance-clerk-to-analyst",
    title: "Finance Clerk → Financial Analyst Pathway",
    category: "Finance",
    description: "Strengthen accuracy, tools, and storytelling with numbers.",
    entryRoles: ["Finance Clerk", "Bookkeeping Assistant", "AP/AR"],
    targetRoles: ["Financial Analyst", "FP&A Analyst"],
    relatedSkills: ["wealth", "career", "mindset"],
    careerInterests: ["business", "management"],
    recommendedCertificationIds: ["quickbooks", "google-data-analytics"],
    recommendedSideHustleIds: ["bookkeeping-basic"],
    milestones: ms("fin", [
      "Eliminate recurring reconciliation errors",
      "Build a monthly close checklist",
      "Learn spreadsheet modeling basics",
      "Complete wealth skill quests consistently",
      "Target analyst roles with clean work samples",
    ]),
    difficulty: "advanced",
    typicalDirection: "Finance analysis",
  },
  {
    id: "security-guard-to-supervisor",
    title: "Security Officer → Security Supervisor",
    category: "Security",
    description: "Add incident leadership, scheduling, and site coordination.",
    entryRoles: ["Security Officer", "Guard"],
    targetRoles: ["Security Supervisor", "Site Lead"],
    relatedSkills: ["career", "health", "mindset"],
    careerInterests: ["management", "healthcare", "trades"],
    recommendedCertificationIds: ["cpr-first-aid", "osha-10"],
    recommendedSideHustleIds: [],
    milestones: ms("secsup", [
      "Write clear incident reports",
      "Learn site emergency procedures deeply",
      "Mentor a new officer",
      "Complete health and mindset consistency quests",
      "Apply for supervisor openings",
    ]),
    difficulty: "starter",
    typicalDirection: "Security supervision",
    disclaimer: "Licensing and firearm/guard card rules vary — verify local requirements.",
  },
  {
    id: "chef-to-kitchen-mgr",
    title: "Cook → Kitchen Manager",
    category: "Hospitality",
    description: "Layer culinary craft with food cost, prep planning, and crew leadership.",
    entryRoles: ["Line Cook", "Prep Cook"],
    targetRoles: ["Kitchen Manager", "Sous Chef"],
    relatedSkills: ["career", "wealth", "health"],
    careerInterests: ["hospitality", "management"],
    recommendedCertificationIds: ["servsafe"],
    recommendedSideHustleIds: ["meal-prep", "catering-assistant"],
    milestones: ms("km", [
      "Own prep lists for a station",
      "Track food waste for one week",
      "Lead a rush with calm communication",
      "Earn/maintain food safety credentials",
      "Ask for KM/sous stretch responsibilities",
    ]),
    difficulty: "intermediate",
    typicalDirection: "Culinary management",
  },
  {
    id: "dev-junior-to-mid",
    title: "Junior Developer → Mid-Level Engineer",
    category: "Technology",
    description: "Move from ticket execution to ownership, testing, and design tradeoffs.",
    entryRoles: ["Junior Developer", "Bootcamp Grad"],
    targetRoles: ["Mid-Level Software Engineer"],
    relatedSkills: ["career", "mindset"],
    careerInterests: ["technology"],
    recommendedCertificationIds: ["freecodecamp-responsive-web", "aws-cloud-practitioner"],
    recommendedSideHustleIds: ["web-services"],
    milestones: ms("dev", [
      "Ship features with tests and clear PRs",
      "Own a small service or module",
      "Write design notes for a change",
      "Complete deep-work mindset quests",
      "Seek mid-level scope in reviews/promos",
    ]),
    difficulty: "advanced",
    typicalDirection: "Software engineering growth",
  },
];

export function getCareerPath(id: string): CareerPath | undefined {
  return CAREER_PATHS.find((p) => p.id === id);
}

export const CAREER_PATH_COUNT = CAREER_PATHS.length;

/** Map shorthand IDs in path definitions onto live catalog IDs. */
const CERT_ID_ALIASES: Record<string, string> = {
  servsafe: "servsafe-food-handler",
  "google-pm": "google-project-mgmt",
  "pmp-google": "google-project-mgmt",
  "pmp-capm": "pmi-capm",
  "comptia-network": "comptia-network-plus",
  "comptia-security": "comptia-security-plus",
  "microsoft-az900": "azure-fundamentals",
  "google-analytics": "google-analytics-ga4",
  "google-ads": "google-ads-search",
  "hubspot-content": "hubspot-content-marketing",
  quickbooks: "quickbooks-online",
};

const HUSTLE_ID_ALIASES: Record<string, string> = {
  "handyman-services": "handyman-odd-jobs",
  "property-support": "house-cleaning",
  "meal-prep": "ebook-guides",
  "event-help": "moving-help",
  "catering-assistant": "house-cleaning",
  "tech-tutoring": "tutoring",
  "device-setup": "tech-support-local",
  "freelance-it": "tech-support-local",
  "affiliate-content": "blog-affiliate",
  "bookkeeping-basic": "bookkeeping-freelance",
  "freelance-pm": "niche-consulting",
  "print-on-demand": "canva-templates",
  "web-services": "freelance-web-dev",
};

export function resolveCertId(id: string): string {
  return CERT_ID_ALIASES[id] ?? id;
}

export function resolveHustleId(id: string): string {
  return HUSTLE_ID_ALIASES[id] ?? id;
}

export function resolvedCertIds(path: CareerPath): string[] {
  return path.recommendedCertificationIds.map(resolveCertId);
}

export function resolvedHustleIds(path: CareerPath): string[] {
  return path.recommendedSideHustleIds.map(resolveHustleId);
}
