export type SideHustle = {
  id: string;
  name: string;
  tagline: string;
  category: "Reseller" | "Digital Products" | "Content" | "Services" | "Local" | "Tech";
  skillLevel: "Beginner" | "Intermediate" | "Advanced";
  startupCost: "Free" | "$" | "$$" | "$$$";
  timeToFirstDollar: string;
  relatedSkills: Array<"health" | "wealth" | "career" | "family" | "mindset">;
  overview: string;
  steps: string[];
  tools: string[];
  pitfalls: string[];
  relatedQuestIdeas: string[];
};

export const SIDE_HUSTLE_CATEGORIES: SideHustle["category"][] = [
  "Reseller",
  "Digital Products",
  "Content",
  "Services",
  "Local",
  "Tech",
];

export const SIDE_HUSTLES: SideHustle[] = [
  {
    id: "thrift-reselling",
    name: "Thrift Reselling",
    tagline: "Buy undervalued thrift finds and flip them online.",
    category: "Reseller",
    skillLevel: "Beginner",
    startupCost: "$",
    timeToFirstDollar: "1-2 weeks",
    relatedSkills: ["wealth", "mindset"],
    overview:
      "Thrift reselling is sourcing clothes, accessories, and housewares from thrift stores, then listing them on marketplaces where buyers already search. Profit depends on research, condition standards, and consistent listing—not lucky one-offs. Typical ranges vary widely by niche and time invested; treat early weeks as skill-building.",
    steps: [
      "Pick one niche (denim, outdoor gear, kids' brands) so you learn comps faster",
      "Check sold listings on eBay or Poshmark before you buy anything",
      "Set a simple buy rule (e.g. item must clear 2–3× after fees and shipping)",
      "Photograph on a clean background with accurate measurements and flaws noted",
      "List 5–10 items per week until you see what sells",
      "Reprice stale inventory every 2 weeks instead of letting it sit forever",
      "Track cost, fees, and net profit in a simple spreadsheet",
    ],
    tools: ["eBay", "Poshmark", "Mercari", "Google Lens", "eBay Terapeak"],
    pitfalls: [
      "Buying based on retail tags instead of recent sold prices",
      "Underestimating shipping weight and marketplace fees",
      "Listing without disclosing stains, odors, or missing buttons",
    ],
    relatedQuestIdeas: [
      "Source and list 10 thrift items this week",
      "Research sold comps for one niche for 30 minutes",
      "Reprice every listing older than 14 days",
    ],
  },
  {
    id: "clearance-flipping",
    name: "Clearance Flipping",
    tagline: "Buy deep retail discounts and resell at normal market prices.",
    category: "Reseller",
    skillLevel: "Beginner",
    startupCost: "$",
    timeToFirstDollar: "1-3 weeks",
    relatedSkills: ["wealth", "career"],
    overview:
      "Clearance flipping means scanning retail clearance for items still in demand online—toys, beauty, tools, seasonal goods. You can earn when the discount is deep enough to cover fees and shipping with margin left. Results vary by store access, season, and how fast you list.",
    steps: [
      "Learn which categories in your stores go on deep clearance regularly",
      "Use your phone to check sold comps before leaving the aisle",
      "Start with small carts ($20–50) to test sell-through",
      "Photograph and list the same day you buy when possible",
      "Keep receipts and SKUs for returns and tax records",
      "Focus on items that ship cheaply and aren't fragile",
      "Rotate away from niches that sit longer than 30–45 days",
    ],
    tools: ["Amazon", "eBay", "Walmart app", "BrickSeek", "Keepa"],
    pitfalls: [
      "Ignoring expiration dates on beauty or food-adjacent goods",
      "Buying restricted brands that marketplaces won't let you sell",
      "Assuming shelf price equals online demand",
    ],
    relatedQuestIdeas: [
      "Run one clearance hunt and list everything the same day",
      "Build a shortlist of 20 brands worth checking weekly",
      "Calculate true net profit on your last 5 sales",
    ],
  },
  {
    id: "sneaker-reselling",
    name: "Sneaker Reselling",
    tagline: "Buy hyped or undervalued sneakers and sell into demand.",
    category: "Reseller",
    skillLevel: "Intermediate",
    startupCost: "$$",
    timeToFirstDollar: "2-4 weeks",
    relatedSkills: ["wealth", "mindset"],
    overview:
      "Sneaker reselling targets releases, restocks, and used pairs that still have buyers. Authentication, condition grading, and fee math matter more than hype. Payoff language should stay honest: margins can shrink fast after fees, shipping, and dead stock.",
    steps: [
      "Study recent sold prices on StockX, GOAT, and eBay for a few models",
      "Decide whether you'll focus on new DS pairs, used pairs, or both",
      "Learn authenticity tells for the brands you plan to touch",
      "Budget for marketplace fees and possible authentication rejects",
      "Photograph box labels, soles, and any wear honestly",
      "Start with lower-risk pairs before chasing limited drops",
      "Track hold time—capital stuck in dead stock is a real cost",
    ],
    tools: ["StockX", "GOAT", "eBay Authenticity Guarantee", "Goat Seller tools", "Discord release calendars"],
    pitfalls: [
      "Buying fakes or damaged pairs you can't authenticate yourself",
      "Ignoring size liquidity—some sizes sit forever",
      "Chasing every drop without a capital and risk limit",
    ],
    relatedQuestIdeas: [
      "Price-check 10 current pairs and log fee-adjusted margins",
      "List one pair with full authenticity photos",
      "Set a weekly max capital budget for sneaker buys",
    ],
  },
  {
    id: "book-reselling",
    name: "Book Reselling",
    tagline: "Scan used books and textbooks that still sell online.",
    category: "Reseller",
    skillLevel: "Beginner",
    startupCost: "$",
    timeToFirstDollar: "1-2 weeks",
    relatedSkills: ["wealth", "career"],
    overview:
      "Book reselling uses barcode scanning and sold-price data to find textbooks, niche nonfiction, and collectible titles. Shipping costs and condition grades decide whether a $3 thrift book is worth it. Earnings vary; consistency and scan discipline matter more than hunting rare first editions.",
    steps: [
      "Install a scanner app and learn condition grades (Like New through Acceptable)",
      "Scan library sales, thrift stores, and used bookstores for positive ROI",
      "Reject books with water damage, heavy highlighting, or missing pages",
      "List on Amazon or eBay with accurate edition and ISBN details",
      "Batch ship with poly mailers and tracking",
      "Cull slow movers before storage costs eat margin",
      "Seasonally watch textbook demand around school calendars",
    ],
    tools: ["Amazon Seller", "eBay", "ScoutIQ", "BookScouter", "Profit Bandit"],
    pitfalls: [
      "Ignoring media mail vs. faster shipping expectations",
      "Listing the wrong edition or ISBN",
      "Holding textbooks through the wrong semester window",
    ],
    relatedQuestIdeas: [
      "Scan 100 books and buy only clear winners",
      "List 15 books with correct condition notes",
      "Ship a batch of sold orders in one trip",
    ],
  },
  {
    id: "electronics-flipping",
    name: "Electronics Flipping",
    tagline: "Buy broken or undervalued gadgets, fix or test, then resell.",
    category: "Reseller",
    skillLevel: "Intermediate",
    startupCost: "$$",
    timeToFirstDollar: "2-4 weeks",
    relatedSkills: ["wealth", "career", "mindset"],
    overview:
      "Electronics flipping focuses on phones, laptops, game consoles, and accessories where testing and light repair unlock value. You can earn when you buy below working-market prices and disclose condition clearly. Returns and DOA units are part of the game—price them into your model.",
    steps: [
      "Pick one category (game consoles or laptops) and learn common failure modes",
      "Test power, ports, screens, and storage before listing",
      "Factor repair parts and your time into the maximum buy price",
      "Wipe devices securely and remove previous accounts",
      "Photograph serial labels and any cosmetic wear",
      "Offer clear return windows to reduce disputes",
      "Keep a parts bin for screens, batteries, and chargers you reuse often",
    ],
    tools: ["eBay", "Facebook Marketplace", "iFixit", "Swappa", "3uTools / manufacturer diagnostics"],
    pitfalls: [
      "Skipping data wipes and account lock checks",
      "Underpricing labor for repairs that take hours",
      "Buying iCloud/FRP-locked devices you can't unlock",
    ],
    relatedQuestIdeas: [
      "Fully test and list one refurbished device",
      "Build a pre-buy checklist for your niche",
      "Calculate profit after returns on your last sale",
    ],
  },
  {
    id: "furniture-flipping",
    name: "Furniture Flipping",
    tagline: "Refinish or restyle used furniture for local cash sales.",
    category: "Reseller",
    skillLevel: "Intermediate",
    startupCost: "$$",
    timeToFirstDollar: "2-6 weeks",
    relatedSkills: ["wealth", "health", "family"],
    overview:
      "Furniture flipping turns thrifted or curb-find pieces into staged, photographed inventory for Marketplace buyers. Profit depends on transport, finish quality, and choosing styles people actually want. Typical margins vary; oversized pieces can eat profit through hauling time alone.",
    steps: [
      "Scout solid-wood pieces with good bones—avoid particleboard disasters",
      "Budget paint, sandpaper, hardware, and delivery/help costs before bidding",
      "Sand, repair, and finish with a clean, consistent look",
      "Stage photos in good light with dimensions clearly listed",
      "Price against local sold comps, not national retail",
      "Offer local pickup first; paid delivery only if the margin supports it",
      "Move unfinished projects quickly—garage inventory compounds",
    ],
    tools: ["Facebook Marketplace", "OfferUp", "Craigslist", "Kreg tools", "orbital sander"],
    pitfalls: [
      "Ignoring lead paint risks on older pieces",
      "Over-refinishing pieces that won't clear the local market",
      "Forgetting transport costs and helper time",
    ],
    relatedQuestIdeas: [
      "Flip one small piece end-to-end this month",
      "Photograph before/after for your listing portfolio",
      "Price three local comps before buying your next piece",
    ],
  },
  {
    id: "sports-card-trading",
    name: "Sports Card Trading",
    tagline: "Buy, grade, and sell singles or sealed product with discipline.",
    category: "Reseller",
    skillLevel: "Intermediate",
    startupCost: "$$",
    timeToFirstDollar: "2-8 weeks",
    relatedSkills: ["wealth", "mindset"],
    overview:
      "Sports card trading is speculation plus liquidity management—singles, sealed wax, and graded slabs all behave differently. You can earn when you buy below clear comps and sell into demand, but prices move fast. Treat it like inventory management, not gambling.",
    steps: [
      "Pick one sport or era so comps become familiar",
      "Learn centering, corners, and surface before paying grading fees",
      "Buy singles with recent sales data, not hope",
      "Use eBay sold filters and stick to fee-adjusted targets",
      "Store cards in sleeves/top loaders to protect condition",
      "Sell into peaks for your niche instead of endless holding",
      "Cap speculative buys as a fixed percent of your capital",
    ],
    tools: ["eBay", "COMC", "PSA", "Card Ladder", "StockX (select cards)"],
    pitfalls: [
      "Paying grading fees on cards that won't grade high enough",
      "Buying sealed product without understanding break odds",
      "Emotional holds after a player news spike fades",
    ],
    relatedQuestIdeas: [
      "Log comps for 20 cards before buying any",
      "List a small lot of singles this week",
      "Set a hard monthly capital limit",
    ],
  },
  {
    id: "garage-sale-arbitrage",
    name: "Garage Sale Arbitrage",
    tagline: "Weekend sourcing from sales and estate clearouts.",
    category: "Reseller",
    skillLevel: "Beginner",
    startupCost: "$",
    timeToFirstDollar: "1-2 weeks",
    relatedSkills: ["wealth", "health", "family"],
    overview:
      "Garage sale arbitrage is early mornings, cash, and quick phone research. Tools, toys, décor, and brand-name goods often sell better online than in a driveway. Payoff depends on how selective you are; hauling junk home is the opposite of profit.",
    steps: [
      "Map Saturday routes with estate and garage sale apps the night before",
      "Bring cash, bags, a measuring tape, and a charged phone",
      "Check sold comps before negotiating",
      "Focus on items that ship easily or sell fast locally",
      "List winners within 48 hours while details are fresh",
      "Bundle slow local items into Marketplace lots",
      "Review weekly: what sold, what sat, what to stop buying",
    ],
    tools: ["Garage Sale Trail", "EstateSales.net", "eBay", "Facebook Marketplace", "Google Lens"],
    pitfalls: [
      "Filling the car with 'maybe' items without comps",
      "Skipping cash discipline and overpaying mid-hype",
      "Leaving purchases unlisted for weeks",
    ],
    relatedQuestIdeas: [
      "Hit three sales and list five finds within 48 hours",
      "Create a route plan for next Saturday",
      "Donate or dump anything unsold after 45 days",
    ],
  },
  {
    id: "retail-arbitrage",
    name: "Retail Arbitrage",
    tagline: "Buy discounted retail stock and sell where demand is higher.",
    category: "Reseller",
    skillLevel: "Intermediate",
    startupCost: "$$",
    timeToFirstDollar: "2-4 weeks",
    relatedSkills: ["wealth", "career"],
    overview:
      "Retail arbitrage bridges local retail discounts and online marketplaces. Success hinges on fees, FBA or shipping costs, and brand restrictions. Typical results vary; treat each buy as a calculated bet with a clear exit.",
    steps: [
      "Choose Amazon FBA, eBay, or both and learn that platform's fee stack",
      "Scan clearance and seasonal markdowns with a profit calculator",
      "Check seller restrictions and hazmat rules before purchasing",
      "Start with small test quantities of each SKU",
      "Photograph and store inventory with SKU labels",
      "Ship or fulfill promptly to protect account health",
      "Cut SKUs that don't sell within your target window",
    ],
    tools: ["Amazon Seller Central", "Keepa", "SellerAmp", "eBay", "inventory spreadsheet"],
    pitfalls: [
      "Ignoring inbound shipping and storage fees",
      "Buying gated brands you can't sell",
      "Scaling a SKU before a test sale confirms demand",
    ],
    relatedQuestIdeas: [
      "Run a 10-item test batch end-to-end",
      "Audit fees on your last three sales",
      "Build a do-not-buy brand list",
    ],
  },
  {
    id: "vintage-clothing",
    name: "Vintage Clothing",
    tagline: "Curate era-specific apparel for style-driven buyers.",
    category: "Reseller",
    skillLevel: "Intermediate",
    startupCost: "$",
    timeToFirstDollar: "2-4 weeks",
    relatedSkills: ["wealth", "career", "mindset"],
    overview:
      "Vintage clothing selling rewards taste, measurement accuracy, and niche branding—90s denim, workwear, band tees, and designer pieces each have different buyers. You can earn when curation is sharp; random thrift piles usually underperform. Sell-through speed varies by platform and aesthetic.",
    steps: [
      "Define a clear aesthetic so your shop looks intentional",
      "Learn fabric tells, era markers, and common fake tells",
      "Measure garments the way buyers expect (pit-to-pit, length, rise)",
      "Wash or spot-clean appropriately before photos",
      "Use consistent lighting and flat lays or mannequin shots",
      "Cross-list on Depop, eBay, or Etsy where your niche lives",
      "Refresh tags and descriptions based on search terms that convert",
    ],
    tools: ["Depop", "eBay", "Etsy", "Grailed", "Vinted"],
    pitfalls: [
      "Mislabeling modern thrift as vintage",
      "Skipping measurements and inviting returns",
      "Inconsistent photos that make the shop look random",
    ],
    relatedQuestIdeas: [
      "Build a 12-item curated drop with one aesthetic",
      "Rewrite titles using buyer search language",
      "Photograph a full outfit flat lay for social proof",
    ],
  },
  {
    id: "printable-planners",
    name: "Printable Planners",
    tagline: "Design PDF planners and sell them as instant downloads.",
    category: "Digital Products",
    skillLevel: "Beginner",
    startupCost: "Free",
    timeToFirstDollar: "1-3 weeks",
    relatedSkills: ["wealth", "career", "mindset"],
    overview:
      "Printable planners are PDF products buyers print at home—daily pages, budget sheets, habit trackers. You build once and can sell repeatedly, though competition is real. Earnings vary with niche specificity, listing quality, and traffic—not with putting 'passive' on the cover.",
    steps: [
      "Pick a narrow niche (teachers, new parents, freelancers) instead of generic planners",
      "Study top Etsy listings for structure, page count, and mockup style",
      "Design clean pages in Canva or Affinity with print-ready margins",
      "Export a sample preview and a full zip of PDFs",
      "Write SEO-aware titles and include size, page count, and use cases",
      "Launch with 1–2 products, then expand based on favorites and questions",
      "Update seasonal covers or bundles to keep listings fresh",
    ],
    tools: ["Canva", "Etsy", "Adobe Acrobat", "Creative Market mockups", "Pinterest"],
    pitfalls: [
      "Launching ultra-generic planners that compete with thousands of clones",
      "Poor PDF export quality or wrong page size",
      "Ignoring customer questions that reveal product gaps",
    ],
    relatedQuestIdeas: [
      "Ship one niche planner listing this week",
      "Create three Pinterest pins for your product",
      "Bundle two related printables into one offer",
    ],
  },
  {
    id: "notion-templates",
    name: "Notion Templates",
    tagline: "Build Notion systems people pay to duplicate.",
    category: "Digital Products",
    skillLevel: "Beginner",
    startupCost: "Free",
    timeToFirstDollar: "1-3 weeks",
    relatedSkills: ["wealth", "career", "mindset"],
    overview:
      "Notion templates package dashboards, CRM boards, habit trackers, and second brains for buyers who want a head start. You can earn by solving a specific workflow well. Sales depend on demos, clarity, and niche—broad 'life OS' templates are crowded.",
    steps: [
      "Solve one painful workflow you personally use (content calendar, job hunt, budget)",
      "Build the template with clear databases, views, and instructions",
      "Record a short Loom walkthrough showing setup in under 5 minutes",
      "Sell via Gumroad, Notion Marketplace, or your own site",
      "Include a duplicate link and a getting-started page inside the template",
      "Collect feedback and ship version updates",
      "Cross-promote with short tutorials that demonstrate the system",
    ],
    tools: ["Notion", "Gumroad", "Loom", "Twitter/X", "Super / Framer landing pages"],
    pitfalls: [
      "Shipping templates with broken relations or empty instruction pages",
      "Copying popular templates without a unique angle",
      "Underpricing support time for confused buyers",
    ],
    relatedQuestIdeas: [
      "Publish one template with a Loom demo",
      "Write a setup guide inside the template",
      "Ask three users what they'd pay to automate",
    ],
  },
  {
    id: "canva-templates",
    name: "Canva Templates",
    tagline: "Sell editable social, resume, and brand kits in Canva.",
    category: "Digital Products",
    skillLevel: "Beginner",
    startupCost: "Free",
    timeToFirstDollar: "1-3 weeks",
    relatedSkills: ["wealth", "career"],
    overview:
      "Canva templates let buyers customize designs without hiring a designer—Instagram kits, media kits, resumes, pitch decks. You can earn when the niche is clear and the files are easy to edit. Income varies with listing quality and how often you refresh styles.",
    steps: [
      "Choose a buyer (real estate agents, coaches, Etsy sellers) and their recurring design needs",
      "Design a cohesive set with shared fonts and colors",
      "Use Canva's template link sharing correctly for commercial sale",
      "Create mockups that show multiple pages in context",
      "List on Etsy or Creative Market with clear edit instructions",
      "Offer a small freebie to grow email or social proof",
      "Update packs seasonally so listings don't look dated",
    ],
    tools: ["Canva Pro", "Etsy", "Creative Market", "Placeit", "Pinterest"],
    pitfalls: [
      "Using non-commercial elements in paid products",
      "Shipping templates that break when buyers change text length",
      "No instructions for how to duplicate and edit",
    ],
    relatedQuestIdeas: [
      "Launch a 10-piece social kit for one niche",
      "Make a 60-second edit tutorial for buyers",
      "Refresh one old listing with new mockups",
    ],
  },
  {
    id: "stock-photo-packs",
    name: "Stock Photo Packs",
    tagline: "Shoot niche photo packs and license them online.",
    category: "Digital Products",
    skillLevel: "Intermediate",
    startupCost: "$",
    timeToFirstDollar: "2-6 weeks",
    relatedSkills: ["wealth", "career", "health"],
    overview:
      "Stock photo packs target underserved niches—specific professions, cultural moments, product flat lays—rather than competing with generic landscapes. Buyers pay for relevance and usage rights. Earnings can build slowly as catalogs grow; one viral pack is not a plan.",
    steps: [
      "Research underserved niches on stock sites and Etsy photo packs",
      "Plan shoots with consistent lighting and model releases when needed",
      "Edit a cohesive set (20–50 images) with similar color grade",
      "License clearly (personal vs. commercial use)",
      "Upload to stock platforms and/or sell packs on Gumroad/Etsy",
      "Keyword carefully—buyer search terms beat poetic titles",
      "Add new packs monthly to compound discoverability",
    ],
    tools: ["Adobe Lightroom", "Shutterstock", "Adobe Stock", "Etsy", "Gumroad"],
    pitfalls: [
      "Uploading without model or property releases",
      "Overly generic subjects that never rank",
      "Inconsistent quality across a pack",
    ],
    relatedQuestIdeas: [
      "Shoot and edit one niche pack of 25 photos",
      "Write commercial license terms for your pack",
      "Upload to two platforms this month",
    ],
  },
  {
    id: "digital-art-prints",
    name: "Digital Art Prints",
    tagline: "Sell downloadable wall art and print-on-demand pieces.",
    category: "Digital Products",
    skillLevel: "Beginner",
    startupCost: "Free",
    timeToFirstDollar: "1-4 weeks",
    relatedSkills: ["wealth", "mindset"],
    overview:
      "Digital art prints are downloadable files buyers print themselves, or POD listings you fulfill through print partners. Style consistency and trending aesthetics help, but trends fade. Typical sales vary; a catalog beats a single masterpiece.",
    steps: [
      "Define a visual style you can repeat (line art, abstract, typography)",
      "Create multiple size ratios (ISO, 2:3, 4:5) for each design",
      "Mock up frames and rooms so buyers can visualize",
      "List digital downloads on Etsy or pair with Printful/Printify",
      "Use searchable titles that match décor intent",
      "Bundle sets of 3 for higher average order value",
      "Track which themes convert and double down",
    ],
    tools: ["Procreate", "Illustrator", "Canva", "Etsy", "Printful"],
    pitfalls: [
      "Selling low-resolution files that blur when printed large",
      "Copying trademarked characters or brand logos",
      "One-off designs with no cohesive shop identity",
    ],
    relatedQuestIdeas: [
      "Publish a 5-print mini collection",
      "Create three lifestyle mockups for one design",
      "Add a 3-pack bundle listing",
    ],
  },
  {
    id: "ebook-guides",
    name: "Niche eBook Guides",
    tagline: "Write short practical guides for a specific audience.",
    category: "Digital Products",
    skillLevel: "Intermediate",
    startupCost: "Free",
    timeToFirstDollar: "3-6 weeks",
    relatedSkills: ["wealth", "career", "mindset"],
    overview:
      "Niche eBooks work when they solve one problem better than a scattered blog post—meal plans for night-shift nurses, first-apartment budgeting, beginner guitar practice plans. You can earn through direct sales or lead magnets that feed other offers. Quality and specificity beat page count.",
    steps: [
      "Interview or survey 5 people in the niche about their exact pain",
      "Outline a short guide (15–40 pages) with checklists and examples",
      "Write in plain language; include templates readers can copy",
      "Design a simple cover and readable interior layout",
      "Sell on Gumroad, Amazon KDP, or your site",
      "Ask early buyers for feedback and testimonials",
      "Turn chapters into social content that points back to the book",
    ],
    tools: ["Google Docs", "Atticus / Vellum", "Canva", "Gumroad", "Amazon KDP"],
    pitfalls: [
      "Writing vague advice anyone could Google in 2 minutes",
      "Launching without proofreaders or sample readers",
      "Pricing like a novel when it's a thin pamphlet—or the reverse",
    ],
    relatedQuestIdeas: [
      "Finish a one-page outline from real interviews",
      "Ship a draft to three beta readers",
      "Publish and share one sample chapter",
    ],
  },
  {
    id: "worksheet-printables",
    name: "Educational Worksheets",
    tagline: "Create printable worksheets for teachers and parents.",
    category: "Digital Products",
    skillLevel: "Beginner",
    startupCost: "Free",
    timeToFirstDollar: "1-3 weeks",
    relatedSkills: ["wealth", "family", "career"],
    overview:
      "Educational worksheets sell to teachers and parents who need ready-to-print practice pages. Grade-level accuracy and clean design matter. Sales can be seasonal around school calendars; ranges vary by subject niche and review quality.",
    steps: [
      "Pick a grade band and subject you can do accurately",
      "Align pages to common skills (phonics, fractions, handwriting)",
      "Design printer-friendly black-and-white or low-ink layouts",
      "Include answer keys where appropriate",
      "List bundles by theme or month on Teachers Pay Teachers or Etsy",
      "Offer a free sample to collect reviews",
      "Update based on teacher feedback and curriculum shifts",
    ],
    tools: ["Canva", "Teachers Pay Teachers", "Etsy", "PowerPoint", "Adobe Acrobat"],
    pitfalls: [
      "Age-inappropriate difficulty or unclear instructions",
      "Copyrighted characters used without permission",
      "No answer key for practice sets that need one",
    ],
    relatedQuestIdeas: [
      "Publish a 10-page worksheet pack with answer key",
      "List one free sample to gather reviews",
      "Build a seasonal bundle for next month",
    ],
  },
  {
    id: "svg-cut-files",
    name: "SVG Cut Files",
    tagline: "Design SVGs for Cricut and Silhouette crafters.",
    category: "Digital Products",
    skillLevel: "Intermediate",
    startupCost: "$",
    timeToFirstDollar: "2-4 weeks",
    relatedSkills: ["wealth", "career"],
    overview:
      "SVG cut files are vector designs crafters use for vinyl, paper, and apparel projects. Clean paths and commercial licenses are table stakes. You can earn with seasonal and niche designs; saturated quote art alone is a hard path.",
    steps: [
      "Learn clean vector practices (closed paths, minimal nodes)",
      "Design for real craft use cases: shirts, decals, cards",
      "Test cut files in Cricut Design Space or Silhouette Studio",
      "Provide usage notes and license terms",
      "List on Etsy with mockups that show craft applications",
      "Create seasonal sets ahead of holidays",
      "Respond quickly to file-compatibility questions",
    ],
    tools: ["Adobe Illustrator", "Inkscape", "Cricut Design Space", "Etsy", "Creative Fabrica"],
    pitfalls: [
      "Shipping broken or overly complex files that won't cut",
      "Using trademarked phrases or characters",
      "Unclear personal vs. commercial license terms",
    ],
    relatedQuestIdeas: [
      "Design and test-cut three SVGs",
      "Launch a holiday mini-bundle",
      "Write clear license text for your shop",
    ],
  },
  {
    id: "mini-online-course",
    name: "Mini Online Course",
    tagline: "Teach one skill in a short paid video course.",
    category: "Digital Products",
    skillLevel: "Intermediate",
    startupCost: "$",
    timeToFirstDollar: "4-8 weeks",
    relatedSkills: ["wealth", "career", "mindset"],
    overview:
      "A mini course packages a transformation you can teach—usually 60–180 minutes of focused video plus worksheets. You can earn when the promise is specific and outcomes are believable. Building the course is work; marketing it is ongoing work.",
    steps: [
      "Define the transformation in one sentence and who it's for",
      "Outline modules that move from setup to first win quickly",
      "Record with decent audio; video polish matters less than clarity",
      "Host on Gumroad, Teachable, or Skool depending on community needs",
      "Include a simple workbook or checklist downloads",
      "Sell to an audience you already have or partner with a niche community",
      "Iterate based on where students get stuck",
    ],
    tools: ["OBS", "Descript", "Gumroad", "Teachable", "Loom"],
    pitfalls: [
      "Building a 10-hour course before validating demand",
      "Weak audio that makes content hard to finish",
      "No clear first-win outcome in the first module",
    ],
    relatedQuestIdeas: [
      "Validate the topic with 10 conversations or pre-orders",
      "Record module one and get feedback",
      "Publish a free 10-minute lesson as a lead-in",
    ],
  },
  {
    id: "preset-packs",
    name: "Photo Preset Packs",
    tagline: "Sell Lightroom or mobile presets to photographers.",
    category: "Digital Products",
    skillLevel: "Intermediate",
    startupCost: "$",
    timeToFirstDollar: "2-4 weeks",
    relatedSkills: ["wealth", "career"],
    overview:
      "Preset packs give photographers a consistent look with one click. They sell best when tied to a style (film, moody, bright & airy) and shown on varied sample images. Results vary; support requests for 'doesn't look like the preview' are common if you skip usage notes.",
    steps: [
      "Develop a cohesive look across 5–15 presets",
      "Test on different lighting conditions and skin tones",
      "Export for Lightroom Classic, Lightroom CC, and mobile if possible",
      "Create before/after marketing images",
      "Sell on your site, Etsy, or photographer marketplaces",
      "Include install instructions for each platform",
      "Update packs when software versions change workflow",
    ],
    tools: ["Adobe Lightroom", "Photoshop", "Etsy", "Gumroad", "FilterGrade"],
    pitfalls: [
      "Preview images that misrepresent what the preset actually does",
      "No install guide for beginners",
      "Too many near-duplicate presets in one pack",
    ],
    relatedQuestIdeas: [
      "Ship a 8-preset pack with install docs",
      "Make five honest before/after examples",
      "Collect feedback from two photographer friends",
    ],
  },
  {
    id: "freelance-writing",
    name: "Freelance Writing",
    tagline: "Write articles, blogs, and web copy for paying clients.",
    category: "Content",
    skillLevel: "Beginner",
    startupCost: "Free",
    timeToFirstDollar: "1-4 weeks",
    relatedSkills: ["wealth", "career"],
    overview:
      "Freelance writing pays for clear thinking and reliable deadlines—blog posts, newsletters, case studies, and product pages. You can earn at widely different rates depending on niche and proof. Early work often builds portfolio more than income; that's normal.",
    steps: [
      "Pick 1–2 niches where you already know the language",
      "Write 2–3 sample pieces if you lack published clips",
      "Pitch or apply with a specific angle, not 'I can write anything'",
      "Use contracts that define revisions, rights, and payment timing",
      "Deliver clean drafts with sources noted when needed",
      "Ask happy clients for referrals and testimonials",
      "Raise rates as turnaround and results improve",
    ],
    tools: ["Google Docs", "Grammarly", "ProWritingAid", "Contently", "LinkedIn"],
    pitfalls: [
      "Working without a deposit or clear scope",
      "Underpricing and attracting endless revision cycles",
      "Accepting topics you can't research accurately",
    ],
    relatedQuestIdeas: [
      "Send five tailored pitches this week",
      "Publish two portfolio samples",
      "Draft a simple one-page contract template",
    ],
  },
  {
    id: "youtube-niche-channel",
    name: "YouTube Niche Channel",
    tagline: "Build a focused channel and monetize through ads and offers.",
    category: "Content",
    skillLevel: "Intermediate",
    startupCost: "$",
    timeToFirstDollar: "3-12 months",
    relatedSkills: ["wealth", "career", "mindset"],
    overview:
      "A niche YouTube channel compounds when topics, thumbnails, and publishing cadence align. Monetization can include ads, affiliates, and digital products—timelines vary a lot. Most channels earn little at first; treat the first months as audience and craft training.",
    steps: [
      "Choose a niche narrow enough to own but wide enough to sustain videos",
      "Study packaging: titles, thumbnails, and first 30 seconds",
      "Batch-record to keep a sustainable schedule",
      "Optimize audio first—viewers forgive average video faster than bad sound",
      "Publish consistently and review analytics for retention drops",
      "Add affiliates or products only after you understand viewer intent",
      "Repurpose long videos into Shorts without relying on Shorts alone",
    ],
    tools: ["YouTube Studio", "DaVinci Resolve", "CapCut", "TubeBuddy", "Descript"],
    pitfalls: [
      "Switching niches every month before learning what works",
      "Clickbait that destroys retention and trust",
      "Expecting ad revenue before watch time exists",
    ],
    relatedQuestIdeas: [
      "Publish four videos in one niche this month",
      "A/B test two thumbnail styles on one topic",
      "Improve audio setup for the next recording",
    ],
  },
  {
    id: "newsletter-sponsorships",
    name: "Newsletter Sponsorships",
    tagline: "Grow an email list and sell relevant sponsor slots.",
    category: "Content",
    skillLevel: "Intermediate",
    startupCost: "Free",
    timeToFirstDollar: "2-6 months",
    relatedSkills: ["wealth", "career", "mindset"],
    overview:
      "Newsletters monetize through sponsorships, paid subscriptions, or product funnels once open rates and niche trust are real. You can earn when advertisers care about your readers—not vanity subscriber counts. Growth is usually slow and compounding.",
    steps: [
      "Pick a reader who has budget and a recurring problem",
      "Publish on a reliable cadence with a clear content promise",
      "Track open rate, click rate, and reply quality",
      "Create a simple media kit with audience demographics and past CTRs",
      "Pitch sponsors whose products you would actually recommend",
      "Start with one sponsor slot; protect reader trust",
      "Repurpose newsletter hits into social content for growth",
    ],
    tools: ["Substack", "Beehiiv", "ConvertKit", "Google Sheets", "Canva"],
    pitfalls: [
      "Selling sponsors before the list has engagement",
      "Spammy ads that tank trust and retention",
      "Inconsistent publishing that kills habit",
    ],
    relatedQuestIdeas: [
      "Write four issues on a fixed schedule",
      "Build a one-page media kit",
      "Pitch two relevant sponsors after 4 consistent issues",
    ],
  },
  {
    id: "tiktok-affiliate",
    name: "Short-Form Affiliate Content",
    tagline: "Create short videos that earn via affiliate links and shops.",
    category: "Content",
    skillLevel: "Beginner",
    startupCost: "Free",
    timeToFirstDollar: "2-8 weeks",
    relatedSkills: ["wealth", "career"],
    overview:
      "Short-form affiliate content uses TikTok, Reels, or Shorts to recommend products with tracked links or in-app shops. You can earn when videos convert, but reach is unpredictable. Disclosure rules and authentic recommendations matter for longevity.",
    steps: [
      "Pick a product category you use and can demonstrate on camera",
      "Join compliant affiliate programs or in-app creator shops",
      "Film native demos—hooks in the first second, proof in the next five",
      "Disclose affiliate relationships clearly",
      "Post consistently and iterate on hooks that hold retention",
      "Track which SKUs convert instead of promoting everything",
      "Build a simple link landing page if the platform requires it",
    ],
    tools: ["TikTok", "Instagram Reels", "Amazon Associates", "Shopify", "CapCut"],
    pitfalls: [
      "Hard-selling products you haven't used",
      "Ignoring FTC/platform disclosure requirements",
      "Chasing trends with zero niche focus",
    ],
    relatedQuestIdeas: [
      "Post daily for 14 days in one niche",
      "Test three hooks for the same product",
      "Set up tracking links and review conversions weekly",
    ],
  },
  {
    id: "podcasting",
    name: "Niche Podcasting",
    tagline: "Host a focused show monetized by sponsors or premiums.",
    category: "Content",
    skillLevel: "Intermediate",
    startupCost: "$",
    timeToFirstDollar: "3-12 months",
    relatedSkills: ["wealth", "career", "mindset"],
    overview:
      "Podcasting builds trust through conversation and expertise. Monetization can include sponsorships, premium feeds, or service leads—usually after consistent listenership. Timelines vary widely; audio quality and niche clarity beat fancy branding early on.",
    steps: [
      "Define the listener and the show's unique angle in one line",
      "Get a decent dynamic mic and quiet recording space",
      "Batch episodes and publish on a schedule you can keep",
      "Write show notes with timestamps and links",
      "Distribute to Apple, Spotify, and YouTube if you want video reach",
      "Pitch sponsors only with real download/listen metrics",
      "Turn episodes into clips for discovery platforms",
    ],
    tools: ["Riverside", "Descript", "Audacity", "Buzzsprout", "Spotify for Podcasters"],
    pitfalls: [
      "Buying expensive gear before confirming a format",
      "Irregular releases that break listener habit",
      "Monetizing before understanding who actually listens",
    ],
    relatedQuestIdeas: [
      "Publish four episodes on a fixed cadence",
      "Improve room treatment for clearer audio",
      "Create five clips from your best episode",
    ],
  },
  {
    id: "blog-affiliate",
    name: "Affiliate Blog",
    tagline: "Publish helpful posts that earn through relevant affiliate links.",
    category: "Content",
    skillLevel: "Intermediate",
    startupCost: "$",
    timeToFirstDollar: "2-6 months",
    relatedSkills: ["wealth", "career"],
    overview:
      "An affiliate blog ranks (or gets shared) for comparison and how-to intent, then earns commissions on recommendations. You can earn when content is genuinely useful and links are relevant. SEO timelines are often months, not days.",
    steps: [
      "Choose a niche with affiliate programs and searchable problems",
      "Build a simple fast site with clear navigation",
      "Write comparison and tutorial posts that answer real questions",
      "Disclose affiliates and only recommend what you'd defend",
      "Update posts when products or pricing change",
      "Build email capture so traffic isn't 100% algorithm-dependent",
      "Track clicks and earnings by post to double down on winners",
    ],
    tools: ["WordPress", "Ghost", "Ahrefs / free keyword tools", "Amazon Associates", "Google Search Console"],
    pitfalls: [
      "Thin content that search engines and readers ignore",
      "Site speed and mobile issues that kill conversions",
      "Linking everything without editorial judgment",
    ],
    relatedQuestIdeas: [
      "Publish two comparison posts this month",
      "Fix Core Web Vitals on your top page",
      "Add disclosures and update three outdated posts",
    ],
  },
  {
    id: "ugc-creator",
    name: "UGC Creator",
    tagline: "Film user-generated-style ads for brands as a freelancer.",
    category: "Content",
    skillLevel: "Intermediate",
    startupCost: "$",
    timeToFirstDollar: "2-6 weeks",
    relatedSkills: ["wealth", "career"],
    overview:
      "UGC creators deliver authentic short videos brands use in paid ads—not necessarily posts on your own profile. You can earn per video or via retainers once you have samples. Rates vary by niche, quality, and whether you include raw files and hooks packages.",
    steps: [
      "Study winning UGC formats in your niche (hooks, demos, testimonials)",
      "Create 3–5 speculative samples for products you like",
      "Build a simple portfolio page or Notion board with examples",
      "Pitch brands and agencies with rates and turnaround times",
      "Deliver vertical video, captions, and hook variations as agreed",
      "Collect testimonials and reuse winning structures",
      "Productize packages (3 videos / 5 hooks) to simplify selling",
    ],
    tools: ["CapCut", "iPhone camera", "Frame.io", "Notion portfolio", "LinkedIn"],
    pitfalls: [
      "Confusing UGC-for-ads with influencer posting deals",
      "No usage-rights clarity in contracts",
      "Underpricing revisions and rush edits",
    ],
    relatedQuestIdeas: [
      "Film three portfolio UGC samples this week",
      "Write a rate card with package options",
      "Pitch ten brands with a relevant sample",
    ],
  },
  {
    id: "stock-footage",
    name: "Stock Footage",
    tagline: "Shoot and license video clips for creators and marketers.",
    category: "Content",
    skillLevel: "Intermediate",
    startupCost: "$$",
    timeToFirstDollar: "1-3 months",
    relatedSkills: ["wealth", "career", "health"],
    overview:
      "Stock footage sellers upload clips that editors search for—workplaces, lifestyle, niches, B-roll. You can earn per download or via subscriptions on stock platforms. Catalog size and keywording drive results more than any single clip.",
    steps: [
      "Research high-demand, underserved clip categories",
      "Shoot stable, well-lit clips in multiple lengths and angles",
      "Edit minimally; deliver clean, usable takes",
      "Keyword thoroughly for how editors actually search",
      "Upload consistently to one or two platforms first",
      "Track which clips earn and plan shoots around winners",
      "Get releases for recognizable people and private property",
    ],
    tools: ["Artgrid / Pond5 / Adobe Stock", "DaVinci Resolve", "a smartphone gimbal", "Frame.io", "spreadsheet tracker"],
    pitfalls: [
      "Uploading shaky, poorly lit footage nobody licenses",
      "Missing model releases",
      "Abandoning uploads after two weekends",
    ],
    relatedQuestIdeas: [
      "Shoot and upload 20 clips in one niche",
      "Improve keywording on your top 10 uploads",
      "Plan a half-day shoot list from demand research",
    ],
  },
  {
    id: "photography-prints-content",
    name: "Photography Content + Prints",
    tagline: "Grow a photo audience and sell prints or licenses.",
    category: "Content",
    skillLevel: "Intermediate",
    startupCost: "$",
    timeToFirstDollar: "1-3 months",
    relatedSkills: ["wealth", "health", "mindset"],
    overview:
      "Photographers can combine social content with print sales, presets, or licensing. The content builds discovery; the product captures value. Earnings vary; local landscapes and niche subjects often convert better than generic pretty pictures.",
    steps: [
      "Pick a recognizable photographic niche and stick to it publicly",
      "Post process consistently so your feed is a brand",
      "Offer prints with clear size and paper options",
      "Use a shop (Shopify, SmugMug, Etsy) with strong mockups",
      "Collect emails from people who love the work",
      "License images to local businesses when relevant",
      "Seasonally launch limited print drops",
    ],
    tools: ["Lightroom", "Instagram", "SmugMug", "Etsy", "Printful"],
    pitfalls: [
      "Posting without a shop path for interested buyers",
      "Inconsistent editing that weakens brand recognition",
      "Underpricing prints after print and shipping costs",
    ],
    relatedQuestIdeas: [
      "Launch a 6-print collection",
      "Post 12 niche images with a cohesive edit",
      "Email a drop to your list or local group",
    ],
  },
  {
    id: "tutoring",
    name: "Tutoring",
    tagline: "Help students learn and charge for focused sessions.",
    category: "Services",
    skillLevel: "Beginner",
    startupCost: "Free",
    timeToFirstDollar: "1-2 weeks",
    relatedSkills: ["wealth", "career", "family"],
    overview:
      "Tutoring is paid 1:1 or small-group teaching in subjects you know well. You can earn locally or online; rates vary by subject, level, and results. Reliability and clear communication often matter as much as subject mastery.",
    steps: [
      "Choose subjects and grade levels you can teach confidently",
      "Set a rate and session length; decide in-person vs. online",
      "Create a simple intake: goals, materials, and availability",
      "List on tutoring platforms and tell local parent networks",
      "Prepare a short diagnostic to start each new student well",
      "Track progress and send brief parent updates",
      "Ask for referrals after successful exam seasons",
    ],
    tools: ["Wyzant", "Tutor.com", "Zoom", "Google Calendar", "Notion"],
    pitfalls: [
      "Accepting subjects you can't teach past a certain level",
      "No cancellation policy",
      "Sessions without goals or homework follow-through",
    ],
    relatedQuestIdeas: [
      "Book your first three paid sessions",
      "Write a one-page tutoring offer flyer",
      "Create a diagnostic worksheet for your subject",
    ],
  },
  {
    id: "freelance-graphic-design",
    name: "Freelance Graphic Design",
    tagline: "Design logos, social assets, and brand materials for clients.",
    category: "Services",
    skillLevel: "Intermediate",
    startupCost: "$",
    timeToFirstDollar: "1-4 weeks",
    relatedSkills: ["wealth", "career"],
    overview:
      "Freelance graphic design sells visual problem-solving—brand kits, ads, packaging, pitch decks. You can earn project fees or retainers. Scope control and tasteful portfolios beat owning every Adobe app.",
    steps: [
      "Build a tight portfolio of 6–10 relevant pieces (spec work is fine at first)",
      "Productize common offers: logo suite, social kit, one-pager",
      "Write proposals with deliverables, rounds of revision, and file types",
      "Find clients via LinkedIn, local businesses, and design job boards",
      "Use contracts and deposits before starting",
      "Deliver organized source files and exports",
      "Request testimonials and case-study permission",
    ],
    tools: ["Figma", "Adobe Illustrator", "Photoshop", "Contra", "Bonsai"],
    pitfalls: [
      "Unlimited revisions without a contract",
      "Starting without a deposit",
      "Portfolio that's too random to signal a niche",
    ],
    relatedQuestIdeas: [
      "Productize one design package with fixed pricing",
      "Send ten outreach messages with portfolio links",
      "Finish a case study for your best project",
    ],
  },
  {
    id: "virtual-assistant",
    name: "Virtual Assistant",
    tagline: "Handle admin, inbox, and ops tasks remotely for busy clients.",
    category: "Services",
    skillLevel: "Beginner",
    startupCost: "Free",
    timeToFirstDollar: "1-3 weeks",
    relatedSkills: ["wealth", "career", "mindset"],
    overview:
      "Virtual assistants save clients time on email, scheduling, research, and light ops. You can earn hourly or via packages once you prove reliability. Specializing (podcast VA, real estate VA, ecom VA) usually beats being 'general admin.'",
    steps: [
      "List tools and tasks you can already do well",
      "Pick a niche client type and learn their recurring workflows",
      "Create package menus (hours/week or task bundles)",
      "Pitch founders and operators with a clear time-saving offer",
      "Use SOPs and shared docs so work is repeatable",
      "Over-communicate status early to build trust",
      "Raise rates as you own higher-leverage tasks",
    ],
    tools: ["Google Workspace", "Notion", "Slack", "Calendly", "Upwork"],
    pitfalls: [
      "Saying yes to tools you've never used without buffer time",
      "No boundaries on after-hours chat",
      "Hourly work with no documented processes",
    ],
    relatedQuestIdeas: [
      "Write a VA services one-pager for one niche",
      "Document an SOP for a task you do weekly",
      "Land one paid trial week",
    ],
  },
  {
    id: "bookkeeping-freelance",
    name: "Freelance Bookkeeping",
    tagline: "Clean up small-business books and monthly reconciliations.",
    category: "Services",
    skillLevel: "Intermediate",
    startupCost: "$",
    timeToFirstDollar: "2-6 weeks",
    relatedSkills: ["wealth", "career"],
    overview:
      "Freelance bookkeepers help solopreneurs and small teams keep clean ledgers, reconcile accounts, and prepare numbers for tax pros. You can earn monthly retainers when you're accurate and discreet. This is not a substitute for CPA licensure—know your lane.",
    steps: [
      "Confirm your skills in QuickBooks or Xero and basic accounting hygiene",
      "Define services: cleanup, monthly bookkeeping, bill pay support",
      "Set clear boundaries vs. tax advice",
      "Get a few practice files or volunteer cleanups for references",
      "Price monthly packages based on transaction volume",
      "Use engagement letters and secure document sharing",
      "Build a referral loop with local accountants",
    ],
    tools: ["QuickBooks Online", "Xero", "Hubdoc", "Google Drive", "practice management spreadsheet"],
    pitfalls: [
      "Giving tax advice without credentials",
      "Messy client document collection with no system",
      "Underpricing cleanup projects that take weeks",
    ],
    relatedQuestIdeas: [
      "Complete a sample cleanup in a sandbox company",
      "Draft an engagement letter template",
      "Reach out to three local CPAs for overflow work",
    ],
  },
  {
    id: "social-media-management",
    name: "Social Media Management",
    tagline: "Plan, create, and post content for local or online brands.",
    category: "Services",
    skillLevel: "Intermediate",
    startupCost: "Free",
    timeToFirstDollar: "2-4 weeks",
    relatedSkills: ["wealth", "career"],
    overview:
      "Social media managers own calendars, creative, posting, and light community reply work. You can earn retainers when you produce consistent content tied to business goals. Vanity metrics alone don't retain clients—leads and engagement quality matter.",
    steps: [
      "Pick an industry (gyms, salons, contractors) and learn what converts",
      "Build a sample content calendar and 5 example posts",
      "Offer a monthly package with clear deliverables",
      "Run a discovery call to clarify offers, brand voice, and CTAs",
      "Batch content and get approvals before the month starts",
      "Report monthly with insights, not just likes",
      "Upsell UGC, ads, or email only after trust is built",
    ],
    tools: ["Later", "Buffer", "Canva", "CapCut", "Meta Business Suite"],
    pitfalls: [
      "Guaranteeing viral reach",
      "No approval workflow—clients surprised by posts",
      "Doing everything custom with no batching system",
    ],
    relatedQuestIdeas: [
      "Create a 30-day sample calendar for one niche",
      "Pitch five local businesses with examples",
      "Write a monthly reporting template",
    ],
  },
  {
    id: "resume-writing",
    name: "Resume Writing",
    tagline: "Rewrite resumes and LinkedIn profiles that get interviews.",
    category: "Services",
    skillLevel: "Beginner",
    startupCost: "Free",
    timeToFirstDollar: "1-2 weeks",
    relatedSkills: ["wealth", "career"],
    overview:
      "Resume writers translate experience into clear, keyword-aware documents for a target role. You can earn per package (resume, cover letter, LinkedIn). Outcomes vary by candidate and market; promise better clarity and positioning, not guaranteed jobs.",
    steps: [
      "Study modern resume norms for your target industries",
      "Create before/after samples (anonymized)",
      "Offer tiered packages with turnaround times",
      "Run intake questionnaires and a short strategy call",
      "Write achievement bullets with metrics when available",
      "Deliver in editable formats plus a PDF",
      "Ask for LinkedIn recommendations and referrals",
    ],
    tools: ["Google Docs", "Teal", "LinkedIn", "Grammarly", "Calendly"],
    pitfalls: [
      "Keyword stuffing that reads like spam",
      "Fabricating metrics the client can't defend in interviews",
      "One-size templates that ignore the target role",
    ],
    relatedQuestIdeas: [
      "Complete two sample resume rewrites",
      "Publish your packages and intake form",
      "Land your first paid resume client",
    ],
  },
  {
    id: "copywriting",
    name: "Freelance Copywriting",
    tagline: "Write sales pages, emails, and ads that convert.",
    category: "Services",
    skillLevel: "Intermediate",
    startupCost: "Free",
    timeToFirstDollar: "2-6 weeks",
    relatedSkills: ["wealth", "career", "mindset"],
    overview:
      "Copywriting focuses on persuasion for landing pages, email sequences, and ads. You can earn project or retainer fees when you understand the offer and customer. Results vary; good discovery beats clever slogans.",
    steps: [
      "Learn a few proven frameworks (PAS, AIDA) without sounding robotic",
      "Build samples: landing page, welcome sequence, ad set",
      "Specialize in a market (coaches, SaaS, ecommerce)",
      "Run discovery to capture voice, objections, and proof",
      "Deliver copy with clear hypotheses and test notes",
      "Price revisions and assets explicitly",
      "Collect conversion anecdotes for your portfolio",
    ],
    tools: ["Google Docs", "Notion", "Figma (for context)", "Hemingway", "Closers Copy or swipe files"],
    pitfalls: [
      "Writing without understanding the offer or buyer",
      "Promising revenue outcomes you don't control",
      "Skipping proof points and relying on hype",
    ],
    relatedQuestIdeas: [
      "Rewrite one weak landing page as a sample",
      "Interview a customer persona for objections",
      "Pitch three businesses with a teardown note",
    ],
  },
  {
    id: "niche-consulting",
    name: "Niche Consulting",
    tagline: "Sell advice in a domain where you already have proof.",
    category: "Services",
    skillLevel: "Advanced",
    startupCost: "Free",
    timeToFirstDollar: "2-6 weeks",
    relatedSkills: ["wealth", "career", "mindset"],
    overview:
      "Niche consulting packages your hard-won experience into paid calls, audits, or implementation plans. You can earn high effective rates when the problem is expensive for the client. Credibility and clear outcomes matter more than a fancy website.",
    steps: [
      "Define the exact problem you solve and for whom",
      "Gather proof: case studies, metrics, portfolio, or career wins",
      "Offer a paid audit or strategy call as the entry product",
      "Create a simple statement of work for longer engagements",
      "Market through LinkedIn, communities, and referrals",
      "Productize repeatable deliverables to avoid custom chaos",
      "Protect time with prep forms and scheduled follow-ups",
    ],
    tools: ["Calendly", "Zoom", "Notion", "LinkedIn", "Stripe"],
    pitfalls: [
      "Consulting on topics where you lack real proof",
      "Scope creep without change orders",
      "Giving away full strategy on free calls",
    ],
    relatedQuestIdeas: [
      "Write a one-sentence consulting offer",
      "Publish one case study or teardown",
      "Book three paid discovery/audit calls",
    ],
  },
  {
    id: "proofreading",
    name: "Proofreading & Editing",
    tagline: "Catch errors and improve clarity for writers and businesses.",
    category: "Services",
    skillLevel: "Beginner",
    startupCost: "Free",
    timeToFirstDollar: "1-3 weeks",
    relatedSkills: ["wealth", "career"],
    overview:
      "Proofreaders and copy editors polish blogs, books, newsletters, and business docs. You can earn per word or per project. Specializing (academic, romance indie authors, SaaS blogs) helps you find repeat clients.",
    steps: [
      "Decide your lane: proofreading only vs. light copyediting",
      "Create a style-sheet habit (AP, Chicago, or client guide)",
      "List services with turnaround and pricing units",
      "Find clients in writer groups, Upwork, and indie author circles",
      "Use tracked changes and clear query comments",
      "Deliver on time—reliability wins renewals",
      "Ask for testimonials after strong deliveries",
    ],
    tools: ["Google Docs", "Microsoft Word", "Grammarly", "PerfectIt", "Upwork"],
    pitfalls: [
      "Editing voice out of the author's work uninvited",
      "Missing consistency issues across long documents",
      "Underestimating time on messy drafts",
    ],
    relatedQuestIdeas: [
      "Complete a timed sample edit for your portfolio",
      "Write a pricing page with per-word rates",
      "Reach out to five indie authors or newsletters",
    ],
  },
  {
    id: "transcription-services",
    name: "Transcription Services",
    tagline: "Turn audio into accurate text for creators and researchers.",
    category: "Services",
    skillLevel: "Beginner",
    startupCost: "Free",
    timeToFirstDollar: "1-2 weeks",
    relatedSkills: ["wealth", "career"],
    overview:
      "Transcription converts interviews, meetings, and podcasts into text. AI helps, but human cleanup still sells for accuracy-sensitive work. Rates vary; speed and confidentiality practices differentiate you.",
    steps: [
      "Test your real words-per-hour speed with a sample file",
      "Set rates for verbatim vs. clean read",
      "Use AI drafts carefully, then human-edit for accuracy",
      "Offer NDAs for sensitive material",
      "Find clients among podcasters, researchers, and journalists",
      "Deliver timestamped docs when useful",
      "Build retainers with recurring shows",
    ],
    tools: ["Descript", "Otter", "Express Scribe", "Google Docs", "Dropbox"],
    pitfalls: [
      "Delivering unedited AI transcripts as finished work",
      "No clarity on verbatim requirements",
      "Poor file security for confidential audio",
    ],
    relatedQuestIdeas: [
      "Transcribe a 20-minute sample for speed benchmarks",
      "Write a service menu (verbatim vs. clean)",
      "Pitch three podcasters with a free sample page",
    ],
  },
  {
    id: "lawn-care",
    name: "Lawn Care",
    tagline: "Mow, edge, and maintain yards on a recurring route.",
    category: "Local",
    skillLevel: "Beginner",
    startupCost: "$$",
    timeToFirstDollar: "1 week",
    relatedSkills: ["wealth", "health"],
    overview:
      "Lawn care is classic local recurring revenue—mowing, edging, and seasonal cleanups. You can earn more with reliability and tidy work than with fancy marketing. Weather, equipment maintenance, and fuel costs affect real take-home.",
    steps: [
      "Check local licensing/insurance expectations for your area",
      "Start with a quality mower, trimmer, and blower you can maintain",
      "Price jobs by yard size and travel time, not guesswork",
      "Flyer nearby neighborhoods and ask early customers for referrals",
      "Build routes by clustering jobs geographically",
      "Offer biweekly or weekly plans for predictable income",
      "Upsell spring/fall cleanups when trust exists",
    ],
    tools: ["Nextdoor", "Facebook Marketplace", "Jobber", "Google Business Profile", "Square"],
    pitfalls: [
      "Underpricing until equipment repairs wipe profits",
      "No rain/cancellation policy",
      "Skipping basic liability protection when you need it",
    ],
    relatedQuestIdeas: [
      "Book five lawns on one geographic route",
      "Create a simple service price sheet",
      "Ask every client for one referral this month",
    ],
  },
  {
    id: "dog-walking",
    name: "Dog Walking",
    tagline: "Walk and check in on pets for busy local owners.",
    category: "Local",
    skillLevel: "Beginner",
    startupCost: "$",
    timeToFirstDollar: "1 week",
    relatedSkills: ["wealth", "health", "family"],
    overview:
      "Dog walking combines reliability, pet sense, and clear communication with owners. You can earn per walk or via midday packages. Trust and safety practices matter as much as loving dogs.",
    steps: [
      "Decide service area and walk lengths you can sustain",
      "Get comfortable with leash skills and basic canine body language",
      "Create profiles for each dog: gear, quirks, emergency contacts",
      "List on Rover/Wag and local community boards",
      "Send photo updates so owners feel in the loop",
      "Use contracts covering keys, cancellations, and incidents",
      "Cluster walks by neighborhood to protect margins",
    ],
    tools: ["Rover", "Wag", "Time To Pet", "Google Maps", "Stripe / Venmo Business"],
    pitfalls: [
      "Taking on reactive dogs beyond your skill level",
      "No backup plan for illness or car trouble",
      "Poor key handling and entry protocols",
    ],
    relatedQuestIdeas: [
      "Complete five-star profile setup on a pet platform",
      "Land three recurring midday walks",
      "Write an emergency protocol checklist",
    ],
  },
  {
    id: "house-cleaning",
    name: "House Cleaning",
    tagline: "Offer reliable residential cleaning on a recurring schedule.",
    category: "Local",
    skillLevel: "Beginner",
    startupCost: "$",
    timeToFirstDollar: "1 week",
    relatedSkills: ["wealth", "health"],
    overview:
      "House cleaning rewards speed, thoroughness, and trust with keys and homes. Recurring clients stabilize income more than one-off deep cleans. Earnings vary by market rates, supplies, and how efficiently you work.",
    steps: [
      "Build a standard checklist for kitchens, baths, floors, and dusting",
      "Price by home size and condition; surcharge for first deep cleans",
      "Buy quality supplies and microfiber systems that speed work",
      "Market via neighbors, Nextdoor, and Google Business Profile",
      "Use a simple booking and payment flow",
      "Protect trust: arrival windows, shoe covers, clear breakage policy",
      "Convert one-offs into biweekly routes",
    ],
    tools: ["Google Business Profile", "Nextdoor", "Jobber", "Square", "TaskRabbit"],
    pitfalls: [
      "No checklist leading to missed spots and bad reviews",
      "Underestimating first-clean time",
      "Weak communication around scheduling",
    ],
    relatedQuestIdeas: [
      "Create your cleaning checklist and supply kit",
      "Book two recurring clients",
      "Ask for Google reviews after great jobs",
    ],
  },
  {
    id: "pressure-washing",
    name: "Pressure Washing",
    tagline: "Clean driveways, siding, and patios for dramatic before/afters.",
    category: "Local",
    skillLevel: "Intermediate",
    startupCost: "$$",
    timeToFirstDollar: "1-2 weeks",
    relatedSkills: ["wealth", "health"],
    overview:
      "Pressure washing sells visual transformation—driveways, sidewalks, patios, and some exteriors. You can earn per job with strong before/after marketing. Technique matters; wrong pressure or chemicals can damage surfaces.",
    steps: [
      "Learn surface-specific techniques and safe detergent use",
      "Buy or rent a capable machine and surface cleaner attachment",
      "Practice on your own property before client work",
      "Price by square footage and soil level",
      "Market with before/after photos on local Facebook groups",
      "Protect landscaping and windows; get consent for chemicals",
      "Add soft washing only after proper training",
    ],
    tools: ["pressure washer", "surface cleaner", "Google Business Profile", "Facebook Marketplace", "Jobber"],
    pitfalls: [
      "Etching concrete or shredding wood with too much pressure",
      "No water runoff or HOA considerations",
      "Underpricing travel and setup time",
    ],
    relatedQuestIdeas: [
      "Complete three before/after job photos for ads",
      "Price out equipment vs. rental for your first month",
      "Flyer one neighborhood after a showcase job",
    ],
  },
  {
    id: "car-detailing",
    name: "Mobile Car Detailing",
    tagline: "Detail cars at clients' homes or offices.",
    category: "Local",
    skillLevel: "Intermediate",
    startupCost: "$$",
    timeToFirstDollar: "1-2 weeks",
    relatedSkills: ["wealth", "health", "career"],
    overview:
      "Mobile detailing brings wash, vacuum, and interior/exterior packages to the customer. You can earn per vehicle with add-ons like clay bar or engine bay cleans. Water access, weather, and product costs shape real margins.",
    steps: [
      "Define packages (interior, exterior, full) with clear inclusions",
      "Assemble a mobile kit: vacuum, towels, chemicals, hose fittings",
      "Practice timing so quotes match reality",
      "Book via Instagram, Facebook, and local offices",
      "Require deposits for mobile appointments",
      "Upsell maintenance plans for repeat revenue",
      "Keep insurance and site permission in mind for apartment lots",
    ],
    tools: ["Instagram", "Square Appointments", "Detailing chemicals kit", "portable vacuum", "Google Business Profile"],
    pitfalls: [
      "Chemical damage from wrong products on coatings or trim",
      "No weather backup plan",
      "Forgetting water/power logistics at the site",
    ],
    relatedQuestIdeas: [
      "Detail three cars and refine your timing",
      "Publish package prices with photos",
      "Land a recurring fleet or family plan",
    ],
  },
  {
    id: "local-photography",
    name: "Local Photography",
    tagline: "Shoot portraits, events, or real estate for nearby clients.",
    category: "Local",
    skillLevel: "Intermediate",
    startupCost: "$$",
    timeToFirstDollar: "2-4 weeks",
    relatedSkills: ["wealth", "career", "family"],
    overview:
      "Local photography businesses sell sessions and image packages—families, grads, small events, or realtor listings. You can earn when delivery is reliable and galleries are easy. Gear helps, but communication and turnaround win referrals.",
    steps: [
      "Pick one primary offering to start (mini sessions or real estate)",
      "Build a portfolio that matches that offering",
      "Create packages with shot counts, timelines, and usage rights",
      "Use contracts and model releases where appropriate",
      "Market in local Facebook groups and partner with related vendors",
      "Deliver galleries quickly with a clear ordering flow",
      "Raise rates as your calendar fills",
    ],
    tools: ["Lightroom", "Pixieset", "HoneyBook", "Instagram", "Canon/Sony body you already own"],
    pitfalls: [
      "No contract or usage-rights clarity",
      "Overbooking without editing time buffers",
      "Saying yes to every genre before you're competent",
    ],
    relatedQuestIdeas: [
      "Run a mini-session day with 4 clients",
      "Write a photography contract template",
      "Partner with one local vendor for referrals",
    ],
  },
  {
    id: "handyman-odd-jobs",
    name: "Handyman Odd Jobs",
    tagline: "Fix small household tasks neighbors don't want to DIY.",
    category: "Local",
    skillLevel: "Intermediate",
    startupCost: "$$",
    timeToFirstDollar: "1-2 weeks",
    relatedSkills: ["wealth", "health", "career"],
    overview:
      "Handyman work covers mounting TVs, fixing fences, assembling furniture, and minor repairs within your skill and permit limits. You can earn hourly or per job. Knowing what not to touch (licensed trades) protects you and clients.",
    steps: [
      "List jobs you can do safely and well; exclude regulated electrical/plumbing if required",
      "Build a basic tool kit and parts run habit",
      "Price site visits and minimums so small jobs stay profitable",
      "Get leads from TaskRabbit, Nextdoor, and referrals",
      "Photograph before/after for trust",
      "Carry appropriate insurance as you scale",
      "Systemize estimates with photo intakes",
    ],
    tools: ["TaskRabbit", "Nextdoor", "Angi", "Jobber", "basic power tool kit"],
    pitfalls: [
      "Attempting licensed trade work illegally",
      "No minimum charge for tiny jobs across town",
      "Poor cleanup leaving a bad last impression",
    ],
    relatedQuestIdeas: [
      "Complete five jobs with photo documentation",
      "Write a menu of fixed-price common tasks",
      "Ask every client for a Google review",
    ],
  },
  {
    id: "pet-sitting",
    name: "Pet Sitting",
    tagline: "House-sit and care for pets while owners travel.",
    category: "Local",
    skillLevel: "Beginner",
    startupCost: "$",
    timeToFirstDollar: "1-2 weeks",
    relatedSkills: ["wealth", "family", "health"],
    overview:
      "Pet sitting includes drop-ins or overnight stays with feeding, meds, and companionship. You can earn more during holidays when demand spikes. Trust, keys, and emergency plans are the product.",
    steps: [
      "Decide drop-in vs. overnight offerings and service radius",
      "Meet pets for a meet-and-greet before booking",
      "Collect vet contacts, medication instructions, and house rules",
      "List on Rover and local community channels",
      "Send updates with photos during stays",
      "Use clear holiday pricing and booking deadlines",
      "Have a backup sitter relationship for emergencies",
    ],
    tools: ["Rover", "Time To Pet", "Google Calendar", "WhatsApp", "lockbox / key system"],
    pitfalls: [
      "Skipping meet-and-greets",
      "Unclear medication handling",
      "No backup when you get sick mid-sit",
    ],
    relatedQuestIdeas: [
      "Complete platform profile with strong photos",
      "Book one weekend sit end-to-end",
      "Write an emergency vet protocol card",
    ],
  },
  {
    id: "moving-help",
    name: "Moving Help",
    tagline: "Be the muscle and organization for local moves.",
    category: "Local",
    skillLevel: "Beginner",
    startupCost: "$",
    timeToFirstDollar: "1 week",
    relatedSkills: ["wealth", "health"],
    overview:
      "Moving helpers load, unload, and assemble basics for people who already have a truck or need extra hands. You can earn hourly with partners. Safety, punctuality, and careful handling of furniture drive tips and repeats.",
    steps: [
      "Partner with a reliable friend if two-person jobs are the norm",
      "Get dollies, blankets, and work gloves",
      "List on moving-help platforms and local boards",
      "Confirm stairs, long carries, and disassembly needs before arrival",
      "Protect floors and corners; move methodically",
      "Price minimum hours and travel clearly",
      "Collect payment promptly and ask for reviews",
    ],
    tools: ["Dolly", "TaskRabbit", "Facebook Marketplace", "moving blankets", "Venmo Business / Square"],
    pitfalls: [
      "Underestimating stairs and time",
      "No clear damage policy",
      "Working alone on unsafe heavy lifts",
    ],
    relatedQuestIdeas: [
      "Complete two moving jobs with a partner",
      "Build a packing/moving checklist for clients",
      "Gather three reviews on your platform of choice",
    ],
  },
  {
    id: "window-washing",
    name: "Window Washing",
    tagline: "Clean residential windows for sparkling before/after results.",
    category: "Local",
    skillLevel: "Beginner",
    startupCost: "$",
    timeToFirstDollar: "1-2 weeks",
    relatedSkills: ["wealth", "health"],
    overview:
      "Window washing is a focused local service with visible payoff. Recurring quarterly clients can stabilize income. Technique and safety on ladders matter; start with ground-floor and simple homes.",
    steps: [
      "Learn a clean method (soap, squeegee, detail towels) that leaves no streaks",
      "Buy quality squeegees, scrubbers, and extension tools",
      "Price by window count and panes; note screens and tracks",
      "Market with before/after photos to nearby streets",
      "Offer interior/exterior packages",
      "Upsell gutter brightening only if skilled",
      "Schedule seasonal reminders for past clients",
    ],
    tools: ["Ettore / Unger tools", "Google Business Profile", "Nextdoor", "Square", "ladder appropriate to jobs"],
    pitfalls: [
      "Unsafe ladder work beyond your training",
      "Streaks from dirty water or poor technique",
      "Forgetting screens and tracks in the quote",
    ],
    relatedQuestIdeas: [
      "Practice full exterior clean on one house",
      "Flyer 50 nearby homes after a showcase job",
      "Book a recurring quarterly client",
    ],
  },
  {
    id: "junk-removal",
    name: "Junk Removal",
    tagline: "Haul away household clutter and charge for speed and muscle.",
    category: "Local",
    skillLevel: "Beginner",
    startupCost: "$$",
    timeToFirstDollar: "1-2 weeks",
    relatedSkills: ["wealth", "health", "career"],
    overview:
      "Junk removal is a local labor business: customers pay to clear basements, garages, estates, and post-move leftovers. You can earn per load when you price for time, dump fees, and fuel—and keep margin by recycling metal or donating usable goods when allowed. Results vary by truck access, disposal costs in your area, and how well you quote before arriving.",
    steps: [
      "Confirm local dump, transfer-station, and donation rules (and any business license needs)",
      "Start with a pickup truck or cargo van plus blankets, dollies, and heavy gloves",
      "Quote by volume and stairs—not vague “cheap haul”—and collect a deposit when possible",
      "Market on Craigslist, Facebook Marketplace, Nextdoor, and Google Business Profile",
      "Separate metal, e-waste, and donate-able items to cut dump fees when legal",
      "Photograph before/after and ask for reviews the same day",
      "Upsell to recurring garage cleanouts or partner with realtors for turnover jobs",
    ],
    tools: ["Pickup truck or cargo van", "appliance dolly", "Facebook Marketplace", "Nextdoor", "Google Business Profile"],
    pitfalls: [
      "Underquoting stairs, heavy appliances, or hazardous items you cannot dump",
      "Ignoring dump fees and fuel until the job is done",
      "Accepting paint, chemicals, or tires without a disposal plan",
    ],
    relatedQuestIdeas: [
      "Price and complete one small garage clear-out this week",
      "Map dump fees and hours for your nearest transfer station",
      "Collect three before/after photos and one Google review",
    ],
  },
  {
    id: "freelance-web-dev",
    name: "Freelance Web Development",
    tagline: "Build and maintain sites for small businesses.",
    category: "Tech",
    skillLevel: "Intermediate",
    startupCost: "Free",
    timeToFirstDollar: "2-6 weeks",
    relatedSkills: ["wealth", "career"],
    overview:
      "Freelance web developers ship marketing sites, landing pages, and small web apps for clients who need something reliable. You can earn per project or via care plans. Scope control and hosting handoff quality often decide whether the project is profitable.",
    steps: [
      "Pick a stack you can deliver fast (Webflow, WordPress, or Next.js)",
      "Create 2–3 demo sites in a niche you want to serve",
      "Productize: brochure site, redesign, landing page sprint",
      "Write proposals with pages, integrations, and revision limits",
      "Use deposits and milestone billing",
      "Hand off with docs: domains, CMS training, analytics",
      "Offer monthly maintenance for updates and backups",
    ],
    tools: ["VS Code", "Webflow", "WordPress", "Vercel", "GitHub"],
    pitfalls: [
      "Open-ended scope with endless feature requests",
      "No maintenance plan after launch",
      "Building custom when a template would meet the goal",
    ],
    relatedQuestIdeas: [
      "Ship a niche demo site this week",
      "Write a fixed-scope website package",
      "Pitch ten local businesses with a teardown",
    ],
  },
  {
    id: "no-code-agency",
    name: "No-Code Agency",
    tagline: "Ship client tools with Bubble, Glide, or FlutterFlow.",
    category: "Tech",
    skillLevel: "Intermediate",
    startupCost: "$",
    timeToFirstDollar: "2-6 weeks",
    relatedSkills: ["wealth", "career", "mindset"],
    overview:
      "No-code freelancers build internal tools, directories, and lightweight apps without traditional engineering timelines. You can earn when you understand workflows and data modeling. Complexity ceilings are real—qualify projects carefully.",
    steps: [
      "Master one platform deeply instead of five shallowly",
      "Learn databases, permissions, and basic UX patterns",
      "Offer MVP sprints with a written feature list",
      "Map client processes before opening the builder",
      "Budget platform fees into client pricing",
      "Document how to maintain the app after handoff",
      "Keep a kill criteria for projects that need custom code",
    ],
    tools: ["Bubble", "Glide", "FlutterFlow", "Airtable", "Make"],
    pitfalls: [
      "Promising scale the platform can't support",
      "Skipping data architecture and painting into a corner",
      "No training for the client's admin user",
    ],
    relatedQuestIdeas: [
      "Rebuild a simple workflow app as a portfolio piece",
      "Write an MVP scoping questionnaire",
      "Deliver one paid prototype sprint",
    ],
  },
  {
    id: "wordpress-fixes",
    name: "WordPress Fixes & Care Plans",
    tagline: "Rescue broken WordPress sites and offer monthly care.",
    category: "Tech",
    skillLevel: "Intermediate",
    startupCost: "Free",
    timeToFirstDollar: "1-3 weeks",
    relatedSkills: ["wealth", "career"],
    overview:
      "Many small businesses run aging WordPress sites that break after updates or plugin conflicts. You can earn on rescue jobs and convert them into maintenance retainers. Security hygiene and backups are part of the service.",
    steps: [
      "Practice staging, backups, and safe update workflows",
      "List common fixes: speed, malware cleanup, form bugs, theme issues",
      "Offer emergency rates and separate care-plan pricing",
      "Find clients via local Facebook groups and agencies needing overflow",
      "Always back up before touching production",
      "Deliver a short health report after each rescue",
      "Automate updates/uptime checks for retainer clients",
    ],
    tools: ["WordPress", "LocalWP", "UpdraftPlus", "Wordfence", "ManageWP"],
    pitfalls: [
      "Editing production without a backup",
      "Unlimited support retainers priced like hosting only",
      "Ignoring PHP/version compatibility issues",
    ],
    relatedQuestIdeas: [
      "Practice a full backup-and-update on a staging site",
      "Publish a WordPress care plan offer",
      "Fix one broken site end-to-end as a case study",
    ],
  },
  {
    id: "shopify-store-setup",
    name: "Shopify Store Setup",
    tagline: "Launch and configure Shopify stores for product sellers.",
    category: "Tech",
    skillLevel: "Intermediate",
    startupCost: "Free",
    timeToFirstDollar: "2-4 weeks",
    relatedSkills: ["wealth", "career"],
    overview:
      "Shopify setup freelancers configure themes, products, payments, and essential apps so merchants can sell. You can earn project fees plus optional retainers for tweaks. Clarity on what 'done' means prevents endless free changes.",
    steps: [
      "Learn Shopify admin, themes, and checkout basics thoroughly",
      "Productize launches: theme setup, product import, pixel installs",
      "Collect brand assets and product data with a checklist",
      "Configure taxes, shipping, and payment methods carefully",
      "QA on mobile before handoff",
      "Train the merchant on fulfilling orders",
      "Offer a 30-day tweak package as an upsell",
    ],
    tools: ["Shopify", "Shopify Theme Editor", "Klaviyo", "Google Analytics", "Looms for training"],
    pitfalls: [
      "Launching without working shipping/tax settings",
      "Installing app bloat that slows the store",
      "No merchant training leading to panic tickets",
    ],
    relatedQuestIdeas: [
      "Build a demo store for a fictional brand",
      "Write a launch checklist clients fill out",
      "Complete one paid store setup",
    ],
  },
  {
    id: "automation-freelance",
    name: "Business Automation Freelance",
    tagline: "Connect apps with Zapier/Make to save clients hours.",
    category: "Tech",
    skillLevel: "Intermediate",
    startupCost: "Free",
    timeToFirstDollar: "2-4 weeks",
    relatedSkills: ["wealth", "career", "mindset"],
    overview:
      "Automation freelancers wire forms, CRMs, spreadsheets, and Slack so work flows without manual copy-paste. You can earn per automation or via monthly ops retainers. The value is hours saved—and fewer human errors—not the number of Zaps.",
    steps: [
      "Map a client's repetitive workflow on a whiteboard first",
      "Build automations with error handling and clear naming",
      "Start with high-ROI wins: lead routing, invoicing pings, onboarding",
      "Document each scenario for the client",
      "Monitor failed runs during a handover week",
      "Price based on complexity and maintenance, not just build time",
      "Offer a monthly care plan for changes",
    ],
    tools: ["Zapier", "Make", "Airtable", "Notion", "Slack"],
    pitfalls: [
      "Automating a broken process instead of fixing it",
      "No error alerts when Zaps fail silently",
      "Overbuilding fragile multi-step flows on day one",
    ],
    relatedQuestIdeas: [
      "Automate one of your own weekly chores as a demo",
      "Write three packaged automation offers",
      "Deliver a paid lead-routing Zap for a client",
    ],
  },
  {
    id: "domain-flipping",
    name: "Domain Flipping",
    tagline: "Buy brandable domains and resell them to startups.",
    category: "Tech",
    skillLevel: "Advanced",
    startupCost: "$$",
    timeToFirstDollar: "1-12 months",
    relatedSkills: ["wealth", "mindset"],
    overview:
      "Domain flipping is speculative inventory: you buy names you believe businesses will want, then list them on marketplaces. You can earn when a buyer needs that exact brand—but many names never sell. Cap risk; this is not a quick paycheck for most people.",
    steps: [
      "Learn what makes a name liquid: length, clarity, extension, brandability",
      "Study comparable sold prices before buying",
      "Start with a small budget and strict buy criteria",
      "List on Afternic, Dan, or Sedo with reasonable BIN prices",
      "Avoid trademark-conflicting names",
      "Renew selectively—don't keep forever-hope inventory",
      "Track holding costs as part of true profit",
    ],
    tools: ["Namecheap", "Google Domains alternatives / registrars", "Dan.com", "Afternic", "NameBio"],
    pitfalls: [
      "Buying trademark-risky names",
      "Overpaying renewals on dead inventory",
      "Expecting fast sales on every registration",
    ],
    relatedQuestIdeas: [
      "Research 20 sold comps in one niche",
      "Buy at most one carefully vetted domain this month",
      "List your portfolio with BIN pricing",
    ],
  },
  {
    id: "micro-saas",
    name: "Micro-SaaS",
    tagline: "Build a tiny paid tool that solves one painful job.",
    category: "Tech",
    skillLevel: "Advanced",
    startupCost: "$",
    timeToFirstDollar: "1-6 months",
    relatedSkills: ["wealth", "career", "mindset"],
    overview:
      "Micro-SaaS is a small software product with recurring billing for a narrow use case. You can earn when the problem is painful and distribution is intentional. Most attempts fail quietly—validate demand before you overbuild.",
    steps: [
      "Find a problem you can reach buyers for (communities you already touch)",
      "Pre-sell or waitlist before building full features",
      "Ship an MVP that does one job reliably",
      "Charge from day one with Stripe",
      "Talk to users weekly and fix activation friction",
      "Keep scope tiny; avoid becoming a platform",
      "Track churn and support load as carefully as signups",
    ],
    tools: ["Next.js", "Stripe", "Supabase", "Plausible", "Twitter/X + niche Discords"],
    pitfalls: [
      "Building for months without a single paying user",
      "Pricing at $0 forever 'for growth'",
      "Feature creep that turns a micro product into a maintenance trap",
    ],
    relatedQuestIdeas: [
      "Interview ten potential users about one workflow",
      "Launch a waitlist landing page this week",
      "Collect your first paid subscriber",
    ],
  },
  {
    id: "app-qa-testing",
    name: "App & Website QA Testing",
    tagline: "Find bugs and write clear reports for product teams.",
    category: "Tech",
    skillLevel: "Beginner",
    startupCost: "Free",
    timeToFirstDollar: "1-3 weeks",
    relatedSkills: ["wealth", "career", "mindset"],
    overview:
      "QA testers break software on purpose and document repro steps. Platforms and indie hackers pay for exploratory testing and device coverage. You can earn per test cycle; clarity of bug reports matters more than finding obscure edge cases alone.",
    steps: [
      "Learn how to write reproducible bug reports (steps, expected, actual)",
      "Practice on public betas and your own projects",
      "Join testing platforms and apply to matching devices/OS",
      "Specialize (mobile, accessibility, checkout flows)",
      "Deliver video repros when text isn't enough",
      "Track time so you know your effective hourly rate",
      "Pitch indie founders directly with a sample report",
    ],
    tools: ["TestFlight", "BrowserStack", "Jira / Linear", "Loom", "uTest"],
    pitfalls: [
      "Vague bugs without repro steps",
      "Testing without understanding acceptance criteria",
      "Burning out on ultra-low platform rates without direct clients",
    ],
    relatedQuestIdeas: [
      "Write five high-quality sample bug reports",
      "Complete one paid test cycle on a platform",
      "Offer a checkout-flow QA audit to an indie SaaS",
    ],
  },
  {
    id: "tech-support-local",
    name: "Local Tech Support",
    tagline: "Help neighbors with computers, Wi-Fi, and device setup.",
    category: "Tech",
    skillLevel: "Beginner",
    startupCost: "$",
    timeToFirstDollar: "1 week",
    relatedSkills: ["wealth", "career", "family"],
    overview:
      "Local tech support solves everyday problems—slow PCs, printer setup, Wi-Fi dead zones, phone transfers. You can earn hourly with travel minimums. Patience and plain-language teaching often generate referrals from older adults and small offices.",
    steps: [
      "List services you can do confidently (and what you won't touch)",
      "Set hourly rates plus a travel minimum",
      "Market on Nextdoor, libraries' bulletin boards, and community Facebook groups",
      "Bring a kit: USB drives, cable adapters, compressed air, notepad",
      "Document changes you made for the client",
      "Offer maintenance visits for updates and cleanups",
      "Avoid sketchy 'hacks' that put client accounts at risk",
    ],
    tools: ["Nextdoor", "Google Business Profile", "TeamViewer / Quick Assist", "Malwarebytes", "Square"],
    pitfalls: [
      "Touching business servers beyond your skill",
      "No backups before major OS changes",
      "Underpricing travel across town for 15-minute fixes",
    ],
    relatedQuestIdeas: [
      "Create a services menu with travel minimums",
      "Help three neighbors and collect testimonials",
      "Build a standard visit checklist",
    ],
  },
  {
    id: "data-cleanup-freelance",
    name: "Spreadsheet & Data Cleanup",
    tagline: "Clean messy sheets, build dashboards, and save team time.",
    category: "Tech",
    skillLevel: "Beginner",
    startupCost: "Free",
    timeToFirstDollar: "1-3 weeks",
    relatedSkills: ["wealth", "career"],
    overview:
      "Many teams drown in messy Google Sheets and Excel files. Cleaning data, building templates, and light dashboards is billable work. You can earn per project; niche knowledge (ecommerce ops, fundraising, inventory) increases rates.",
    steps: [
      "Showcase before/after screenshots of messy-to-clean sheets",
      "Learn useful formulas, pivot tables, and data validation",
      "Offer fixed packages: cleanup, template build, dashboard",
      "Ask for sample (anonymized) data in discovery",
      "Document how to maintain the sheet after handoff",
      "Find clients in ops communities and among solopreneurs",
      "Upsell automation once the data model is clean",
    ],
    tools: ["Google Sheets", "Excel", "Airtable", "Make", "Notion"],
    pitfalls: [
      "Editing live sheets without a backup copy",
      "Building fragile formulas nobody understands",
      "Scope creep into full analytics engineering",
    ],
    relatedQuestIdeas: [
      "Publish a template that solves one ops problem",
      "Clean one messy sample workbook as a portfolio piece",
      "Pitch five small businesses a sheet audit",
    ],
  },
  {
    id: "ai-content-ops",
    name: "AI-Assisted Content Ops",
    tagline: "Help businesses use AI tools without shipping sloppy content.",
    category: "Tech",
    skillLevel: "Intermediate",
    startupCost: "Free",
    timeToFirstDollar: "2-4 weeks",
    relatedSkills: ["wealth", "career", "mindset"],
    overview:
      "Businesses want AI speed with human quality control. This hustle sets up prompts, workflows, and editorial checks for blogs, support macros, and social drafts. You can earn setup fees plus retainers; honesty about limits builds trust.",
    steps: [
      "Pick a vertical and map their recurring content types",
      "Build prompt libraries and review checklists that prevent hallucinations",
      "Deliver a workflow: brief → draft → human edit → publish",
      "Train the client on what AI should never write unsupervised",
      "Measure time saved and revision quality",
      "Productize monthly content ops hours",
      "Stay current on tool changes without chasing every shiny model",
    ],
    tools: ["ChatGPT", "Claude", "Notion", "Descript", "Google Docs"],
    pitfalls: [
      "Publishing unedited AI content under the client's name",
      "Promising full replacement of human experts",
      "No factual review step for sensitive topics",
    ],
    relatedQuestIdeas: [
      "Build a prompt + QA checklist for one content type",
      "Run a two-week pilot with one business",
      "Document time saved in a simple report",
    ],
  },
];

export function getSideHustleById(id: string): SideHustle | undefined {
  return SIDE_HUSTLES.find((h) => h.id === id);
}
