import type { QuestCatalogItem } from "./types";

export const CAREER_QUESTS: QuestCatalogItem[] = [
  { id: "cat-career-001", title: "Write today's top 3 outcomes", description: "Three things, that is it", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-002", title: "Clear 10 old emails", description: "Reclaim attention", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-003", title: "Update your task list", description: "Trust the system", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-004", title: "Send one thank-you message at work", description: "Relationship compound interest", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-005", title: "Block 25 minutes of focus time", description: "Protect deep work", category: "career", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-career-006", title: "Tidy your digital desktop", description: "Visual calm", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-007", title: "Review tomorrow's calendar", description: "No ambush meetings", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-008", title: "Document one small process note", description: "Future you will thank you", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-009", title: "Ask one clarifying question", description: "Reduce rework", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-010", title: "Stand and stretch between meetings", description: "Body keeps the score", category: "career", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-career-011", title: "Update LinkedIn headline or about", description: "Signal who you are", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-012", title: "Save a useful article to read later", description: "Build a learning queue", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-013", title: "Prepare talking points for a meeting", description: "Show up sharp", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-014", title: "Clean up file names in one folder", description: "Findability", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-015", title: "Send a progress update unprompted", description: "Manage up lightly", category: "career", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-career-016", title: "Practice a 60-second self-intro", description: "Clarity under pressure", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-017", title: "End the day with a shutdown ritual", description: "Close the loops", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-018", title: "Identify one bottleneck on a project", description: "Name the constraint", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-019", title: "Compliment a coworker's specific work", description: "Culture you can feel", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-020", title: "Turn off nonessential notifications 1 hour", description: "Attention diet", category: "career", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-career-021", title: "Add tomorrow's first task tonight", description: "Morning momentum", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-022", title: "Review a rejected idea without ego", description: "Extract the lesson", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-023", title: "Update your resume bullet draft", description: "Keep evidence warm", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-024", title: "Schedule a short walk between calls", description: "Reset cognition", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-025", title: "Confirm a deadline in writing", description: "Shared reality", category: "career", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-career-026", title: "Organize browser bookmarks for work", description: "Tooling hygiene", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-027", title: "Read one page of a career book", description: "Slow compound", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-028", title: "Practice saying no once politely", description: "Protect capacity", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-029", title: "Capture three wins from this week", description: "Evidence folder", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-030", title: "Check project status board", description: "See the board, work the board", category: "career", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-career-031", title: "Arrive 5 minutes early to a call", description: "Calm start", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-032", title: "Write a clearer subject line habit", description: "Respect inboxes", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-033", title: "Mute a noisy chat channel temporarily", description: "Signal to noise", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-034", title: "Back up important work files", description: "Disaster prevention", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-035", title: "Learn one shortcut in your main tool", description: "Speed compounds", category: "career", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-career-036", title: "Offer help on a small teammate task", description: "Social capital", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-037", title: "Review industry job posts for skills", description: "Market awareness", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-038", title: "Set a meeting-free focus block", description: "Deep work appointment", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-039", title: "Draft questions for your next 1:1", description: "Own the agenda", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-040", title: "Clean slack/teams unread to zero once", description: "Inbox hygiene", category: "career", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-career-041", title: "Update status for stakeholders", description: "Reduce chase-downs", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-042", title: "Practice posture on camera", description: "Presence", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-043", title: "List skills you used today", description: "Self-inventory", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-044", title: "Thank a mentor or peer", description: "Tend the network", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-045", title: "Close three open loops on your list", description: "Completion bias for good", category: "career", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-career-046", title: "Prep clothes or bag for tomorrow", description: "Professional friction down", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-047", title: "Read your company's goals page", description: "Align local work", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-048", title: "Turn a vague task into a next action", description: "Specificity", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-049", title: "Share a useful resource with the team", description: "Lift others", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-050", title: "Log time on a project honestly", description: "See where hours go", category: "career", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-career-051", title: "Practice a difficult sentence out loud", description: "Hard conversations", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-052", title: "Unsubscribe from low-value newsletters", description: "Attention reclaim", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-053", title: "Set an end-of-work alarm", description: "Boundaries", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-054", title: "Review one metric you influence", description: "Own a number", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-055", title: "Write a brag document entry", description: "Promotion fuel", category: "career", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-career-056", title: "Check calendar for focus conflicts", description: "Defend the deep work", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-057", title: "Rename a messy project folder", description: "Ops clarity", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-058", title: "Send a calendar invite with agenda", description: "Respect time", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-059", title: "Do a 5-minute desk reset", description: "Environment cues focus", category: "career", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-career-060", title: "Identify one skill to practice this week", description: "Deliberate growth", category: "career", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-career-061", title: "Deep work block for 60 minutes", description: "No meetings, no chat", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-062", title: "Ship a draft without over-polishing", description: "Feedback beats perfection", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-063", title: "Document a process end-to-end", description: "Build the system that frees you", category: "career", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-career-064", title: "Have one networking conversation", description: "Stay top of mind", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-065", title: "Finish a certification study module", description: "Stay sharp", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-066", title: "Prepare a portfolio piece update", description: "Proof of skill", category: "career", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-career-067", title: "Run a short retrospective on a project", description: "Improve the machine", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-068", title: "Mentor someone for 20 minutes", description: "Teaching sharpens you", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-069", title: "Negotiate scope on an overloaded request", description: "Protect quality", category: "career", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-career-070", title: "Build a weekly priority plan", description: "Calendar the wins", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-071", title: "Record a loom or demo of your work", description: "Make progress visible", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-072", title: "Practice a presentation out loud", description: "Reps before stage", category: "career", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-career-073", title: "Clean up a backlog ruthlessly", description: "Kill zombie tasks", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-074", title: "Write a project brief", description: "Alignment upfront", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-075", title: "Ask for feedback on recent work", description: "Grow faster", category: "career", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-career-076", title: "Map stakeholders for a project", description: "Politics is information", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-077", title: "Automate one repetitive task", description: "Buy back time", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-078", title: "Update case study metrics", description: "Numbers tell the story", category: "career", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-career-079", title: "Do a skills gap analysis", description: "Honest roadmap", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-080", title: "Schedule informational interview", description: "Learn adjacent roles", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-081", title: "Ship a small internal tool or template", description: "Leverage for the team", category: "career", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-career-082", title: "Practice interview answers for 30 min", description: "Career optionality", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-083", title: "Lead a meeting with a clear agenda", description: "Own the room", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-084", title: "Resolve a lingering conflict item", description: "Clear the fog", category: "career", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-career-085", title: "Write a proposal or one-pager", description: "Influence on paper", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-086", title: "Shadow a colleague in another function", description: "Cross-functional IQ", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-087", title: "Review OKRs or goals mid-cycle", description: "Course correct", category: "career", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-career-088", title: "Build a personal CRM of contacts", description: "Network as asset", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-089", title: "Complete a stretch assignment chunk", description: "Visible growth", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-090", title: "Improve a slide or doc for clarity", description: "Communication craft", category: "career", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-career-091", title: "Set up a weekly review ritual", description: "ops cadence", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-092", title: "Learn a tool feature deeply for 45 min", description: "Craft", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-093", title: "Draft a raise or promo narrative", description: "Story + evidence", category: "career", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-career-094", title: "Cut a low-impact recurring meeting", description: "Time reclaim", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-095", title: "Create a checklist for a recurring job", description: "Error proofing", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-096", title: "Do customer or user interview notes", description: "Reality check", category: "career", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-career-097", title: "Publish internal knowledge share", description: "Thought leadership lite", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-098", title: "Pair program or cowork on hard problem", description: "Two brains", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-099", title: "Audit your calendar for energy leaks", description: "Design the week", category: "career", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-career-100", title: "Write postmortem notes on a miss", description: "Blameless learning", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-101", title: "Build a 30-60-90 plan for a goal", description: "Structure", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-102", title: "Practice saying strategic nos", description: "Capacity leadership", category: "career", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-career-103", title: "Update GitHub or public work samples", description: "Portable proof", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-104", title: "Research salary bands for your role", description: "Market data", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-105", title: "Facilitate a brainstorm with constraints", description: "Creative ops", category: "career", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-career-106", title: "Improve onboarding notes for next hire", description: "Scale yourself", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-107", title: "Block time for learning weekly", description: "Non-negotiable growth", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-108", title: "Deliver tough feedback kindly", description: "Leadership reps", category: "career", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-career-109", title: "Align with manager on priorities", description: "Shared scoreboard", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-110", title: "Create a decision log for a project", description: "Memory for teams", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-111", title: "Refactor a messy work system", description: "Reduce drag", category: "career", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-career-112", title: "Prepare metrics dashboard snapshot", description: "Show the story", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-113", title: "Do a competitive or industry scan", description: "Context", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-114", title: "Ship a customer-facing improvement", description: "Impact", category: "career", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-career-115", title: "Practice storytelling for your project", description: "Narrative skill", category: "career", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-career-116", title: "Finish a hard career milestone project", description: "Ship what matters", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-117", title: "Complete a certification exam sitting", description: "Credential unlocked", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-118", title: "Lead a cross-team initiative", description: "Influence without authority", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-119", title: "Negotiate a raise, rate, or title", description: "Ask with evidence", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-120", title: "Land an interview or pitch meeting", description: "Pipeline in motion", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-121", title: "Publish a case study of your work", description: "Public proof", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-122", title: "Build a 90-day skill sprint and finish week 1", description: "Deliberate practice", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-123", title: "Deliver a high-stakes presentation", description: "Own the room", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-124", title: "Ship a portfolio overhaul", description: "Best work forward", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-125", title: "Resolve a major project risk", description: "Unstick the critical path", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-126", title: "Complete a leadership course module", description: "Level the soft skills", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-127", title: "Launch an internal process change", description: "System upgrade", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-128", title: "Write and submit a conference talk idea", description: "Visibility", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-129", title: "Close a sale, deal, or key approval", description: "Outcome owned", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-130", title: "Build a hiring loop or scorecard", description: "Raise the bar", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-131", title: "Complete a stretch goal early", description: "Reliability brand", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-132", title: "Transition into a new responsibility", description: "Identity shift", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-133", title: "Create a personal brand content piece", description: "Signal expertise", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-134", title: "Run a full project from brief to launch", description: "End-to-end ownership", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-135", title: "Get a recommendation or referral lined up", description: "Social proof", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-136", title: "Overhaul your weekly operating system", description: "Second brain for work", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-137", title: "Complete a difficult stakeholder alignment", description: "Politics with integrity", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-138", title: "Ship open-source or public contribution", description: "Community resume", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-139", title: "Design a career ladder plan for 12 months", description: "Direction", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-140", title: "Turn around an underperforming metric", description: "Ownership", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-141", title: "Facilitate a strategy offsite segment", description: "Senior presence", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-142", title: "Build a freelance or consulting offer page", description: "Optionality", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-143", title: "Pass a technical or skills assessment", description: "Prove readiness", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-144", title: "Mentor someone through a milestone", description: "Multiply impact", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-145", title: "Cut scope to hit a critical deadline", description: "Tradeoff leadership", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-146", title: "Create a department template library", description: "Force multiplier", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-147", title: "Secure budget for a tool or initiative", description: "Resourcefulness", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-148", title: "Complete a multi-week learning path", description: "Credentialed growth", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-149", title: "Document your promotion packet", description: "Make it undeniable", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-career-150", title: "Lead incident response or crisis calm", description: "Reliability under fire", category: "career", difficulty: "hard", xpReward: 50, isDaily: false },
];
