import type { QuestCatalogItem } from "./types";

export const FAMILY_QUESTS: QuestCatalogItem[] = [
  { id: "cat-family-001", title: "Text someone you care about", description: "Tend the people that matter", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-002", title: "Send a voice note instead of text", description: "Warmth travels farther", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-003", title: "Give a specific compliment", description: "Be the reason someone smiles", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-004", title: "Put phone away for one shared meal", description: "Presence over pixels", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-005", title: "Ask an open-ended question at home", description: "Learn who they are becoming", category: "family", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-family-006", title: "Do a 5-minute tidy of a shared space", description: "Respect the commons", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-007", title: "Plan a small kindness for tomorrow", description: "Intention beats impulse", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-008", title: "Hug someone longer than usual", description: "Oxytocin is free", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-009", title: "Write a short thank-you note", description: "Old-school, high impact", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-010", title: "Listen fully without fixing", description: "Witness before advice", category: "family", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-family-011", title: "Share a memory with family", description: "Story is glue", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-012", title: "Check in on a friend you miss", description: "Rekindle lightly", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-013", title: "Put a shared event on the calendar", description: "Make it real", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-014", title: "Make tea or coffee for someone", description: "Service as love language", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-015", title: "Say I appreciate you out loud", description: "Do not assume they know", category: "family", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-family-016", title: "Clear one fridge leftover together", description: "Team chore", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-017", title: "Play one quick game together", description: "Play is bonding", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-018", title: "Look at old photos for 10 minutes", description: "Shared history", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-019", title: "Leave a sticky-note encouragement", description: "Surprise warmth", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-020", title: "Confirm weekend plans early", description: "Reduce friction", category: "family", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-family-021", title: "Water plants or feed pets mindfully", description: "Care practice", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-022", title: "Ask about someone's day and wait", description: "Curiosity", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-023", title: "Put devices in a basket during dinner", description: "House rule trial", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-024", title: "Send a meme that fits their humor", description: "Light connection", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-025", title: "Offer to take a chore off their plate", description: "Relieve load", category: "family", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-family-026", title: "Practice patience in one tense moment", description: "Choose response", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-027", title: "Celebrate a small win out loud", description: "Cheerleading", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-028", title: "Call a relative you usually text", description: "Voice matters", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-029", title: "Sit outside together briefly", description: "Shared air", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-030", title: "Pack a snack or lunch for someone", description: "Practical love", category: "family", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-family-031", title: "Repair a small household annoyance", description: "Care for the nest", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-032", title: "Say sorry cleanly if you snapped", description: "Repair fast", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-033", title: "Put kids' or partner's event first tonight", description: "Priority signal", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-034", title: "Share one gratitude about home life", description: "Notice the good", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-035", title: "Start a shared playlist", description: "Soundtrack of us", category: "family", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-family-036", title: "Read a short story aloud", description: "Cozy literacy", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-037", title: "Do dishes without being asked", description: "Silent service", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-038", title: "Plan a phone-free hour at home", description: "Attention gift", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-039", title: "Ask how you can help this week", description: "Collaborative load", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-040", title: "Update a family shared list", description: "Ops of love", category: "family", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-family-041", title: "Smile and greet household members", description: "Climate setting", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-042", title: "Leave the nicer portion for them", description: "Generosity", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-043", title: "Remember a preference and act on it", description: "Detail love", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-044", title: "Send calendar invite for date or hang", description: "Protect the slot", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-045", title: "Teach or learn a tiny skill together", description: "Side-by-side growth", category: "family", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-family-046", title: "Check school or family messages", description: "Stay in the loop", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-047", title: "Put laundry away as a team", description: "Shared finish", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-048", title: "Light a candle or set a cozy vibe", description: "Atmosphere", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-049", title: "Tell a story from your day", description: "Invite reciprocity", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-050", title: "Do a 2-minute appreciation round", description: "Ritual", category: "family", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-family-051", title: "Text a photo from today to family", description: "Share the mundane magic", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-052", title: "Hold the door / carry something", description: "Small chivalry", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-053", title: "Ask about a hobby they love", description: "Enter their world", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-054", title: "Put phones to charge outside bedroom", description: "Sleep and intimacy", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-055", title: "Write tomorrow's family priority", description: "One shared focus", category: "family", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-family-056", title: "Forgive a small irritation today", description: "Do not collect stamps", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-057", title: "Invite someone to join an errand", description: "Errands as togetherness", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-058", title: "Check in about emotional weather", description: "How are we really?", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-059", title: "Make the bed with care", description: "Order as respect", category: "family", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-family-060", title: "End the day with a kind goodnight", description: "Close the loop warmly", category: "family", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-family-061", title: "Spend 30 minutes phone-free with loved ones", description: "Presence over pixels", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-062", title: "Cook a meal together", description: "Kitchen as connection", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-063", title: "Plan a family or friend outing", description: "Make memories on purpose", category: "family", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-family-064", title: "Have a screen-free evening activity", description: "Board game, walk, talk", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-065", title: "Write a longer letter or email of thanks", description: "Depth", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-066", title: "Do a chore as a team end-to-end", description: "Build little teammates", category: "family", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-family-067", title: "Schedule a date night or friend hang", description: "Protect the relationship", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-068", title: "Have a values conversation", description: "What matters to us", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-069", title: "Visit or call an elder relative", description: "Tend the roots", category: "family", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-family-070", title: "Host a simple hangout at home", description: "Hospitality", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-071", title: "Create a shared budget for fun", description: "Money without fights", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-072", title: "Attend a kid or friend event fully present", description: "Show up", category: "family", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-family-073", title: "Resolve one lingering household issue", description: "Clear the residue", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-074", title: "Build a weekly family meeting agenda", description: "Ops for home", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-075", title: "Volunteer together for 1 hour", description: "Shared purpose", category: "family", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-family-076", title: "Plan meals for the household for 3 days", description: "Reduce decision fatigue", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-077", title: "Take photos and actually send them", description: "Share the album", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-078", title: "Learn a partner or child's interest deeply", description: "Enter their world", category: "family", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-family-079", title: "Do a technology boundaries reset", description: "Agreements, not lectures", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-080", title: "Write anniversary or birthday plan early", description: "Thoughtfulness", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-081", title: "Have a hard conversation with kindness", description: "Truth + care", category: "family", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-family-082", title: "Create a chore chart that feels fair", description: "Justice at home", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-083", title: "Spend one-on-one time with each kid/partner", description: "Undivided", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-084", title: "Organize a shared space together", description: "Environment = calm", category: "family", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-family-085", title: "Practice an apology and repair fully", description: "Attachment safety", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-086", title: "Start a weekly tradition (even tiny)", description: "Ritual glue", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-087", title: "Support someone's goal with a concrete help", description: "Allyship", category: "family", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-family-088", title: "Plan a weekend without overbooking", description: "Margin for people", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-089", title: "Cook someone's favorite meal", description: "Love language: food", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-090", title: "Do errands that unburden the household", description: "Invisible labor visible", category: "family", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-family-091", title: "Have a money talk without blame", description: "Team finances", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-092", title: "Write family emergency info sheet", description: "Care is preparedness", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-093", title: "Limit work talk at dinner intentionally", description: "Roles off", category: "family", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-family-094", title: "Plan a gratitude practice as a household", description: "Shared mindset", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-095", title: "Reconcile with someone you drifted from", description: "Bridge rebuild", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-096", title: "Attend community or faith gathering", description: "Belonging", category: "family", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-family-097", title: "Build a shared photo book or album", description: "Story artifact", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-098", title: "Practice active listening exercise 20 min", description: "Skill of intimacy", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-099", title: "Take a class or hobby together", description: "Side-by-side novelty", category: "family", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-family-100", title: "Set holiday expectations early", description: "Prevent December fights", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-101", title: "Do a digital detox morning with family", description: "Slow start", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-102", title: "Help with homework or learning patiently", description: "Scaffold, do not take over", category: "family", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-family-103", title: "Create a quiet co-working hour at home", description: "Parallel presence", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-104", title: "Plan a picnic or outdoor time", description: "Cheap joy", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-105", title: "Discuss boundaries and needs calmly", description: "Adulting together", category: "family", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-family-106", title: "Celebrate someone else's milestone big", description: "Generosity of attention", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-107", title: "Deep-clean a room as a team", description: "Shared sweat", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-108", title: "Write wills or emergency contacts update", description: "Love as paperwork", category: "family", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-family-109", title: "Host a game night", description: "Laughter protocol", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-110", title: "Check in on a friend in hard season", description: "Show up in weather", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-111", title: "Plan childcare or alone time swap", description: "Sustain the caregivers", category: "family", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-family-112", title: "Create a shared reading ritual", description: "Books beat noise", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-113", title: "Do a relationship check-in (roses/thorns)", description: "Weekly pulse", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-114", title: "Cook and deliver a meal to someone", description: "Care beyond the house", category: "family", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-family-115", title: "Unplug social media for an evening together", description: "Local life first", category: "family", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-family-116", title: "Plan and execute a full family day", description: "Memories on purpose", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-117", title: "Have a major relationship repair talk", description: "Courage + care", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-118", title: "Take a weekend trip or day trip", description: "Shared adventure", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-119", title: "Establish a household operating system", description: "Chores, calendar, money", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-120", title: "Support a loved one through a hard week", description: "Reliable presence", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-121", title: "Host a meaningful gathering", description: "Community building", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-122", title: "Complete a home project together", description: "Build the nest", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-123", title: "Start couples or family counseling if needed", description: "Ask for help", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-124", title: "Reconcile a long conflict", description: "Bridge the gap", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-125", title: "Create a family mission statement", description: "North star", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-126", title: "Plan caregiving logistics thoughtfully", description: "Adulting for elders/kids", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-127", title: "Do a device-free weekend day", description: "Radical presence", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-128", title: "Organize important family documents", description: "Legacy ops", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-129", title: "Celebrate a milestone with real effort", description: "Ritualize joy", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-130", title: "Move through a parenting challenge as a team", description: "United front", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-131", title: "Build a monthly friend tradition", description: "Sustain the village", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-132", title: "Forgive something heavy (process, not bypass)", description: "Emotional work", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-133", title: "Plan estate or guardianship basics", description: "Protect the people", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-134", title: "Take responsibility publicly for a miss", description: "Repair at scale", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-135", title: "Create a family health emergency plan", description: "Prepared love", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-136", title: "Spend a full day serving someone else's needs", description: "Generosity", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-137", title: "Cut a toxic pattern with accountability", description: "Boundaries that stick", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-138", title: "Plan a reunion or long-distance visit", description: "Distance bridged", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-139", title: "Build a support network map", description: "Who helps whom", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-140", title: "Finish a shared creative project", description: "Make something together", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-141", title: "Navigate a school or medical advocacy issue", description: "Show up hard", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-142", title: "Reset household finances as a team", description: "Shared money story", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-143", title: "Take parental leave planning seriously", description: "If relevant", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-144", title: "Do a digital legacy / photo archive day", description: "Preserve story", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-145", title: "Commit to a weekly date for 4 weeks", description: "Consistency", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-146", title: "Help a friend move or through crisis", description: "Muscle for community", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-147", title: "Write letters to future family", description: "Time-capsule care", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-148", title: "Establish screen rules that everyone keeps", description: "Culture change", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-149", title: "Complete a home safety upgrade", description: "Locks, kits, readiness", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-family-150", title: "Mark a hard anniversary with care", description: "Grief and love", category: "family", difficulty: "hard", xpReward: 50, isDaily: false },
];
