import type { QuestCatalogItem } from "./types";

export const HEALTH_QUESTS: QuestCatalogItem[] = [
  { id: "cat-health-001", title: "Drink a full glass of water on waking", description: "Start hydrated before caffeine", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-002", title: "Take a 10-minute walk", description: "Easy movement that clears your head", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-003", title: "Do 20 bodyweight squats", description: "Wake up the legs", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-004", title: "Stretch your hips for 5 minutes", description: "Desk bodies need this", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-005", title: "Prep a protein-forward breakfast", description: "Fuel before you scramble", category: "health", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-health-006", title: "Floss tonight", description: "Two minutes, future-you smiles", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-007", title: "Stand up every hour today", description: "Break the sit-streak", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-008", title: "Eat one serving of fruit", description: "Simple micronutrient win", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-009", title: "Take vitamins or meds on time", description: "Consistency beats intensity", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-010", title: "Go to bed 20 minutes earlier", description: "Sleep debt compounds fast", category: "health", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-health-011", title: "Do 10 push-ups (any variation)", description: "Progress, not perfection", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-012", title: "Drink water before each meal", description: "Appetite and energy both improve", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-013", title: "Park farther and walk in", description: "Steal steps from the day", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-014", title: "Take the stairs once", description: "Tiny cardio bank deposit", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-015", title: "Foam roll for 5 minutes", description: "Unstick what training tightens", category: "health", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-health-016", title: "Log how you feel after lunch", description: "Notice energy dips", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-017", title: "Put sunscreen on if outdoors", description: "Boring, effective longevity", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-018", title: "Swap soda for sparkling water once", description: "Keep the ritual, ditch the sugar", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-019", title: "Do a 2-minute plank", description: "Core under load", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-020", title: "Pack a healthy snack", description: "Beat the vending machine", category: "health", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-health-021", title: "Wash your face before bed", description: "Recovery starts with skin", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-022", title: "Open a window for fresh air", description: "Oxygen is underrated", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-023", title: "Do 15 lunges per side", description: "Unilateral strength", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-024", title: "Eat slowly for one meal", description: "Digestion is part of fitness", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-025", title: "Set a phone bedtime alarm", description: "Protect the night", category: "health", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-health-026", title: "Do calf raises while brushing teeth", description: "Habit stacking", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-027", title: "Drink herbal tea after dinner", description: "Wind-down cue", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-028", title: "Walk during one phone call", description: "Meeting miles", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-029", title: "Add vegetables to dinner", description: "Volume without junk", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-030", title: "Do shoulder rolls for 1 minute", description: "Release desk tension", category: "health", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-health-031", title: "Check posture at your desk", description: "Ears over shoulders", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-032", title: "Fill a water bottle and finish it", description: "Visible hydration target", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-033", title: "Do 30 jumping jacks", description: "Quick heart-rate bump", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-034", title: "Stretch your chest doorway-style", description: "Undo keyboard hunch", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-035", title: "Choose grilled over fried once", description: "One cleaner swap", category: "health", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-health-036", title: "Put workout clothes out tonight", description: "Reduce tomorrow friction", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-037", title: "Take 5 deep belly breaths", description: "Nervous system reset", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-038", title: "Skip a second helping", description: "Stop at satisfied", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-039", title: "Walk after dinner for 10 minutes", description: "Glucose and mood", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-040", title: "Do wrist and finger stretches", description: "Hands earn their keep", category: "health", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-health-041", title: "Track sleep bedtime tonight", description: "Awareness first", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-042", title: "Eat breakfast without scrolling", description: "Presence with fuel", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-043", title: "Do 10 glute bridges", description: "Wake the posterior chain", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-044", title: "Stand while watching one show segment", description: "Passive time, active legs", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-045", title: "Cut caffeine after 2pm", description: "Sleep quality lever", category: "health", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-health-046", title: "Do neck mobility gently", description: "Careful, controlled", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-047", title: "Prep tomorrow lunch ingredients", description: "Future hunger handled", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-048", title: "Take shoes off and walk barefoot indoors", description: "Foot strength", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-049", title: "Ice a sore spot for 10 minutes", description: "Simple recovery", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-050", title: "Choose water at a restaurant", description: "Default healthier", category: "health", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-health-051", title: "Do cat-cow for 1 minute", description: "Spine love", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-052", title: "Eat sitting down, not rushed standing", description: "Nervous system meal", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-053", title: "Schedule tomorrow workout on calendar", description: "Make it real", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-054", title: "Do 10 slow dead bugs", description: "Core control", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-055", title: "Replace dessert with fruit once", description: "Sweet without spiral", category: "health", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-health-056", title: "Wash produce when you get home", description: "Ready-to-eat wins", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-057", title: "Cold 30-second shower finish", description: "Short discipline dose", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-058", title: "Do ankle circles both sides", description: "Joint prep", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-059", title: "Pack gym shoes by the door", description: "Friction killer", category: "health", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-health-060", title: "Sip broth or soup as a starter", description: "Volume before calories", category: "health", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-health-061", title: "Complete a 30-minute workout", description: "Any modality that raises heart rate", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-062", title: "Cook a balanced meal from scratch", description: "Protein + produce + carbs", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-063", title: "Hit 8,000+ steps today", description: "Movement volume", category: "health", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-health-064", title: "Mobility session for 20 minutes", description: "Long-term joint insurance", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-065", title: "Meal prep two lunches", description: "Remove weekday friction", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-066", title: "Strength train major lifts", description: "Push, pull, hinge, squat", category: "health", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-health-067", title: "No alcohol today", description: "Clear head experiment", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-068", title: "Get 7+ hours of sleep", description: "Non-negotiable recovery", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-069", title: "Do a zone-2 cardio session", description: "Conversational pace, real work", category: "health", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-health-070", title: "Track macros for one day", description: "Data without obsession", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-071", title: "Yoga or mobility flow 25 minutes", description: "Move with intention", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-072", title: "Walk 45 minutes outdoors", description: "Nature + steps", category: "health", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-health-073", title: "Hit protein target for the day", description: "Build and repair", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-074", title: "Do a full warm-up before training", description: "Earn the hard sets", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-075", title: "Batch-cook a protein source", description: "Ready for the week", category: "health", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-health-076", title: "Complete a HIIT session", description: "Short, honest intensity", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-077", title: "Do a recovery workout on purpose", description: "Show up easy intentionally", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-078", title: "Stretch before bed for 15 minutes", description: "Downshift the body", category: "health", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-health-079", title: "No ultra-processed snacks today", description: "Whole-food day", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-080", title: "Bike or swim for 30 minutes", description: "Cross-train the engine", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-081", title: "Practice a sport skill 30 minutes", description: "Play is training", category: "health", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-health-082", title: "Clear junk food from the fridge", description: "Environment design", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-083", title: "Do 3 sets of pull exercises", description: "Back and arms", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-084", title: "Do 3 sets of push exercises", description: "Chest and shoulders", category: "health", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-health-085", title: "Hike a local trail", description: "Legs and lungs", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-086", title: "Try a new healthy recipe", description: "Expand the menu", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-087", title: "Weigh and log breakfast accurately", description: "Calibration day", category: "health", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-health-088", title: "Complete a core circuit", description: "Anti-fragile midsection", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-089", title: "Foam roll + stretch combo 20 min", description: "Soft tissue care", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-090", title: "Drink only water, tea, or black coffee", description: "Clean beverage day", category: "health", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-health-091", title: "Do farmer carries or loaded walks", description: "Real-world strength", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-092", title: "Practice nasal breathing on a walk", description: "Calm cardio", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-093", title: "Stand or walk for 1 focused hour", description: "Reduce sit time", category: "health", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-health-094", title: "Meal plan the next 3 days", description: "Decide once, eat easy", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-095", title: "Do a posture-focused workout", description: "Pull more than you push", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-096", title: "Finish a shortened workout anyway", description: "Show-up streak", category: "health", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-health-097", title: "Pack gym bag the night before", description: "Friction killer", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-098", title: "Do single-leg strength work", description: "Balance and durability", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-099", title: "Safe short cold exposure protocol", description: "Controlled stress", category: "health", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-health-100", title: "Track resting heart rate", description: "Readiness signal", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-101", title: "Replace one takeout with home cooking", description: "Margin + health", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-102", title: "Do a full-body circuit", description: "Efficient coverage", category: "health", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-health-103", title: "Practice good form on one lift", description: "Quality over ego", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-104", title: "Grocery shop with a list only", description: "No aisle improvising", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-105", title: "Do interval hill walking", description: "Free conditioning", category: "health", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-health-106", title: "Stretch hip flexors thoroughly", description: "Desk countermeasure", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-107", title: "Prep a protein smoothie", description: "Fast nutrient hit", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-108", title: "Complete physical therapy homework", description: "Rehab is training", category: "health", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-health-109", title: "Do breathwork for 10 minutes", description: "Downshift intensity", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-110", title: "Easy bike 40 minutes active recovery", description: "Keep blood moving", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-111", title: "Cook vegetables two ways tonight", description: "Volume eating", category: "health", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-health-112", title: "Do grip work hangs or farmers", description: "Underrated strength", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-113", title: "Schedule annual checkup if due", description: "Maintenance mode", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-114", title: "Practice a mobility hold", description: "Own the range", category: "health", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-health-115", title: "No screens during meals today", description: "Digest and notice", category: "health", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-health-116", title: "Complete a hard training session", description: "Leave something honest in the gym", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-117", title: "7-day workout streak checkpoint", description: "Show the calendar who is boss", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-118", title: "Run or walk a 5K", description: "Finish the distance", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-119", title: "Hit protein target 5 days this week", description: "Consistency over vibes", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-120", title: "Sleep 7+ hours five nights this week", description: "Recovery campaign", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-121", title: "Train for 60+ focused minutes", description: "Deep work for the body", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-122", title: "Complete a race or timed challenge", description: "Measure yourself", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-123", title: "Cut out added sugar for 3 days", description: "Reset the palate", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-124", title: "Build a 4-week training plan", description: "Program, then follow", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-125", title: "Safe PR on a lift or distance", description: "Earn a new ceiling", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-126", title: "Full rest-and-rebuild protocol day", description: "Sleep, protein, walk, stretch", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-127", title: "Meal prep an entire week", description: "Sunday future-you gift", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-128", title: "Complete a long hike (2+ hours)", description: "Endurance + outdoors", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-129", title: "Follow a deload week correctly", description: "Discipline includes restraint", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-130", title: "Pass a fitness test you set", description: "Your rules, your finish", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-131", title: "No junk food for a full week", description: "Environment + will", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-132", title: "Learn and note one lift cue", description: "Teach to lock it in", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-133", title: "Schedule bloodwork or checkup", description: "Adulting as athletics", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-134", title: "Complete a challenging fitness class", description: "Show up and finish", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-135", title: "Keep a morning health routine 5 days", description: "Stack that sticks", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-136", title: "Ruck or weighted walk 45+ minutes", description: "Carry your future", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-137", title: "Swim continuously 20+ minutes", description: "Full-body cardio", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-138", title: "Strict bedtime for 7 nights", description: "Sleep architecture", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-139", title: "Hit step goal every day this week", description: "Volume streak", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-140", title: "Cook every dinner at home 5 nights", description: "Kitchen as training adjacent", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-141", title: "Complete a rehab plan milestone", description: "Pain down, capacity up", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-142", title: "Do a max-effort interval day", description: "Hard, then recover", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-143", title: "Build a home emergency fitness kit", description: "Bands, mat, readiness", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-144", title: "Join a team or training partner", description: "Accountability", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-145", title: "Honest body recomposition check-in", description: "Photos, tape, energy", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-146", title: "Train despite low motivation (safe)", description: "Identity over mood", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-147", title: "Create injury-prevention routine 3x", description: "Prehab", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-148", title: "Finish a fitness course module", description: "Learn the why", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-149", title: "Volunteer at an active charity event", description: "Move for more than you", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-health-150", title: "Complete a full rest week with walks only", description: "Strategic recovery", category: "health", difficulty: "hard", xpReward: 50, isDaily: false },
];
