import type { QuestCatalogItem } from "./types";

export const MINDSET_QUESTS: QuestCatalogItem[] = [
  { id: "cat-mindset-001", title: "Journal for 5 minutes", description: "Get the noise on paper", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-002", title: "Write 3 gratitudes", description: "Cheap, powerful, repeat", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-003", title: "Read 10 pages", description: "Compound your mind", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-004", title: "Meditate for 5 minutes", description: "Train the inner muscle", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-005", title: "Learn one new word", description: "Vocabulary is leverage", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-mindset-006", title: "Do a 2-minute brain dump", description: "Empty the RAM", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-007", title: "Set an intention for the day", description: "Aim before you rush", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-008", title: "Notice one automatic thought", description: "Awareness is step one", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-009", title: "Take 10 slow breaths", description: "Downshift", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-010", title: "Write a worry then park it", description: "Contain the spiral", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-mindset-011", title: "Read a poem or short essay", description: "Dense nutrition", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-012", title: "Practice a posture of confidence 1 min", description: "Body leads mind", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-013", title: "Say a useful affirmation you believe", description: "No fluff — earned words", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-014", title: "Review yesterday's lesson in one line", description: "Close the loop", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-015", title: "Sit quietly without input 3 minutes", description: "Boredom training", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-mindset-016", title: "Write a fear as a testable claim", description: "Defang it", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-017", title: "Stretch while naming 3 senses", description: "Grounding", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-018", title: "Delete one comparison trigger account", description: "Protect the mind", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-019", title: "Listen to one focused podcast segment", description: "Learn while you move", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-020", title: "Sketch or doodle for 5 minutes", description: "Right brain open", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-mindset-021", title: "Write a kind note to yourself", description: "Self-respect reps", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-022", title: "Practice single-tasking one chore", description: "Attention muscle", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-023", title: "Name your emotion precisely", description: "Granularity helps", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-024", title: "Read a page of philosophy or wisdom", description: "Long view", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-025", title: "Do a gratitude text to yourself log", description: "Private win log", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-mindset-026", title: "Visualize the next hard thing calmly", description: "Rehearse success", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-027", title: "Replace one complaint with a request", description: "Agency", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-028", title: "Tidy a corner as mindfulness", description: "Order outside, order inside", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-029", title: "Write tomorrow's MIT (most important)", description: "Decide once", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-030", title: "Practice smiling in a hard moment", description: "State shift", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-mindset-031", title: "Limit news to a set window", description: "Information diet", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-032", title: "Recite a memorized passage", description: "Mind fitness", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-033", title: "Do a body scan for 3 minutes", description: "Interoception", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-034", title: "Write what you can control today", description: "Circle of control", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-035", title: "Celebrate effort, not just outcome", description: "Process praise", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-mindset-036", title: "Ask what would make today meaningful", description: "Purpose microdose", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-037", title: "Practice beginner mind on a familiar task", description: "Curiosity", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-038", title: "Log a win before bed", description: "End on agency", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-039", title: "Read something that challenges you", description: "Growth discomfort", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-040", title: "Do a digital Sabbath hour", description: "Silence", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-mindset-041", title: "Write a values word for the week", description: "Compass", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-042", title: "Notice a judgment and soften it", description: "Compassion reps", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-043", title: "Practice box breathing 4 rounds", description: "Nervous system", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-044", title: "Study one cognitive bias example", description: "Mental models", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-045", title: "Write a letter you will not send", description: "Catharsis", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-mindset-046", title: "Memorize a quote that steadies you", description: "Anchor", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-047", title: "Observe thoughts on a walk", description: "Moving meditation", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-048", title: "Turn a failure into a lesson note", description: "Alchemize", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-049", title: "Practice patience in a queue", description: "Daily dojo", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-050", title: "Set a tiny learning goal for today", description: "1% better", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-mindset-051", title: "Avoid multitasking for one hour", description: "Deep attention", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-052", title: "Write three options before deciding", description: "Expand the map", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-053", title: "Do a tech-free morning start", description: "Own the first hour", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-054", title: "Practice reframing one setback", description: "Cognitive flexibility", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-055", title: "Listen more than you speak once", description: "Humility", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-mindset-056", title: "Read notes from a past breakthrough", description: "Remember capability", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-057", title: "Sit with discomfort 90 seconds", description: "Urge surfing", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-058", title: "Write a definition of enough today", description: "Counter scarcity", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-059", title: "Ask a better question in your journal", description: "Quality inquiry", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-mindset-060", title: "End doomscroll with a book open", description: "Pattern interrupt", category: "mindset", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-mindset-061", title: "Study with focus for 30 minutes", description: "Deep focus on a skill", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-062", title: "Meditate for 15 minutes", description: "Longer stillness", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-063", title: "Write a full journal entry", description: "Process the day", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-mindset-064", title: "Read for 30 uninterrupted minutes", description: "Deep literacy", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-065", title: "Complete a tutorial in your field", description: "Sharpen the edge", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-066", title: "Practice active recall on a topic", description: "Test yourself", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-mindset-067", title: "Do a weekly review of goals", description: "Course correct", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-068", title: "Write a personal manifesto page", description: "Identity on paper", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-069", title: "Therapy or coaching homework session", description: "Do the work", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-mindset-070", title: "Learn a mental model and apply it", description: "Latticework", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-071", title: "Digital declutter for 30 minutes", description: "Attention environment", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-072", title: "Practice a hard conversation script", description: "Rehearse courage", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-mindset-073", title: "Do a values-to-calendar audit", description: "Time tells truth", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-074", title: "Write a fear-setting exercise", description: "Define the monster", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-075", title: "Complete a mindfulness class session", description: "Guided skill", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-mindset-076", title: "Build a reading list for the month", description: "Intentional inputs", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-077", title: "Teach a concept to someone", description: "Feynman technique", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-078", title: "Do a silent walk for 40 minutes", description: "No podcast, just mind", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-mindset-079", title: "Write morning pages (3 sides)", description: "Clear the channel", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-080", title: "Practice delayed gratification once", description: "Choose long game", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-081", title: "Analyze a decision with pros/cons/risks", description: "Better judgment", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-mindset-082", title: "Create a not-to-do list", description: "Subtraction", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-083", title: "Study a biography chapter", description: "Model excellence", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-084", title: "Do exposure to a mild fear safely", description: "Expand comfort zone", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-mindset-085", title: "Write a forgiveness letter process", description: "Put down the weight", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-086", title: "Plan a deep work week theme", description: "One priority", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-087", title: "Limit social media to 20 minutes", description: "Hard cap", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-mindset-088", title: "Practice stoic evening review", description: "What did I do well?", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-089", title: "Learn and use one new framework", description: "Thinking tools", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-090", title: "Do a gratitude visit or long message", description: "Depth gratitude", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-mindset-091", title: "Rewrite a limiting belief with evidence", description: "CBT lite", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-092", title: "Complete a puzzle or strategy game mindfully", description: "Focus play", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-093", title: "Attend a meetup or class for growth", description: "New inputs", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-mindset-094", title: "Build a second brain note for a topic", description: "Externalize knowledge", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-095", title: "Practice public speaking for 20 min", description: "Voice under pressure", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-096", title: "Do a life area score 1-10 check-in", description: "Dashboard of self", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-mindset-097", title: "Write a letter from future you", description: "Perspective", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-098", title: "Implement a morning routine for 3 days", description: "Identity stack", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-099", title: "Study logic or critical thinking exercise", description: "Reasoning", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-mindset-100", title: "Unfollow comparison triggers in bulk", description: "Curate feeds", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-101", title: "Practice acceptance of an uncontrollable", description: "Serenity skill", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-102", title: "Do a creative constraint challenge", description: "Innovation under limits", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-mindset-103", title: "Journal on relationships patterns", description: "Insight", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-104", title: "Complete a spaced-repetition review", description: "Memory science", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-105", title: "Write goals that are specific and dated", description: "Clarity", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-mindset-106", title: "Practice mindfulness during a chore", description: "Ordinary presence", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-107", title: "Read research summary on a habit", description: "Evidence-based self", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-108", title: "Do a digital sunset 90 min before bed", description: "Protect sleep mind", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-mindset-109", title: "Build an anti-procrastination plan", description: "If-then implementation", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-110", title: "Reflect on a role model behavior to copy", description: "Steal like a learner", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-111", title: "Practice radical honesty in one safe talk", description: "Integrity", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-mindset-112", title: "Create a personal curriculum for 30 days", description: "Self-school", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-113", title: "Meditate on compassion for 10 minutes", description: "Warm mind", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-114", title: "Write a pre-mortem for a goal", description: "Anticipate failure modes", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-mindset-115", title: "Do a weekly solitude block", description: "Hear yourself think", category: "mindset", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-mindset-116", title: "Finish a full book", description: "Front to back, no skimming", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-117", title: "Complete a course module end-to-end", description: "Stack the wins", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-118", title: "Maintain a 7-day meditation streak", description: "Stillness habit", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-119", title: "Write a long-form personal essay", description: "Think on paper", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-120", title: "Do a silent half-day retreat at home", description: "Deep reset", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-121", title: "Finish a challenging nonfiction book section", description: "Heavy lift for mind", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-122", title: "Complete therapy milestone or breakthrough work", description: "Real processing", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-123", title: "Build and keep a 30-day habit tracker", description: "Identity evidence", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-124", title: "Ship a learning project publicly", description: "Accountability", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-125", title: "Memorize and perform a piece (talk/poem)", description: "Owned knowledge", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-126", title: "Complete a digital detox weekend", description: "Reclaim attention", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-127", title: "Write a 5-year vision then reverse-plan", description: "Long arc", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-128", title: "Master a difficult mental skill chunk", description: "Deliberate practice", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-129", title: "Lead a study group session", description: "Teach to learn", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-130", title: "Finish a certification study guide pass", description: "Exam ready", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-131", title: "Practice cold approach learning (ask experts)", description: "Courageous curiosity", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-132", title: "Complete a creativity project start to finish", description: "Make the thing", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-133", title: "Do a fear inventory and act on one item", description: "Courage agenda", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-134", title: "Establish a weekly deep thinking block month-long", description: "Strategy time", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-135", title: "Rewrite your personal narrative truthfully", description: "Identity edit", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-136", title: "Complete a philosophy or wisdom book", description: "Depth", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-137", title: "Build a second brain system and migrate notes", description: "Knowledge ops", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-138", title: "Maintain no-complaint challenge for 3 days", description: "Agency language", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-139", title: "Finish a spaced learning course path", description: "Retention", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-140", title: "Do a values-aligned life audit weekend", description: "Course correct hard", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-141", title: "Publish thoughtful content from your learning", description: "Signal", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-142", title: "Complete a mindfulness intensive series", description: "Skill depth", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-143", title: "Confront a major avoidance with a plan", description: "Face it", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-144", title: "Write and live a rule of life for 2 weeks", description: "Monastic lite", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-145", title: "Achieve a learning PR (speed/accuracy)", description: "Measure growth", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-146", title: "Mentor someone through a mindset shift", description: "Transmission", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-147", title: "Finish a research deep-dive with notes", description: "Scholarship", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-148", title: "Practice radical responsibility for a week", description: "Own your side", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-149", title: "Design and run a personal experiment", description: "Test, do not guess", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-mindset-150", title: "Complete a transformative workshop or retreat", description: "Step change", category: "mindset", difficulty: "hard", xpReward: 50, isDaily: false },
];
