import type { QuestCatalogItem } from "./types";

export const WEALTH_QUESTS: QuestCatalogItem[] = [
  { id: "cat-wealth-001", title: "Log every purchase today", description: "Awareness before optimization", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-002", title: "Check account balances", description: "Know the scoreboard", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-003", title: "Transfer $5 to savings", description: "Tiny automatic win", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-004", title: "Cancel one unused subscription", description: "Leak plugged", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-005", title: "Price-compare one upcoming buy", description: "Five minutes of leverage", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-wealth-006", title: "Pack lunch instead of buying", description: "Margin in a bag", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-007", title: "Make coffee at home", description: "Latte math, real dollars", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-008", title: "Open your budgeting app", description: "Face the numbers", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-009", title: "Move money to an emergency fund", description: "Floor under your life", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-010", title: "Review one recurring bill", description: "Hunt the silent raise", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-wealth-011", title: "Unsubscribe from promo emails", description: "Fewer impulse triggers", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-012", title: "List three wants vs needs", description: "Clarify the urge", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-013", title: "Set a no-spend evening", description: "Entertainment without checkout", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-014", title: "Check credit card statement", description: "Catch errors early", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-015", title: "Put spare change toward savings", description: "Micro-savings", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-wealth-016", title: "Write tomorrow spending intention", description: "Decide before the aisle", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-017", title: "Skip one delivery fee", description: "Walk or cook", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-018", title: "Update net worth snapshot", description: "Assets minus liabilities", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-019", title: "Read one page of a money book", description: "Compound literacy", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-020", title: "Turn off one-click checkout", description: "Add friction to impulse", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-wealth-021", title: "Check interest rates on savings", description: "Are you earning anything?", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-022", title: "Photograph receipts into tracker", description: "Clean books", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-023", title: "Ask for a student or loyalty discount", description: "Polite money", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-024", title: "Plan meals before grocery run", description: "List beats craving", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-025", title: "Delete saved shopping carts", description: "Out of sight", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-wealth-026", title: "Review tipping defaults", description: "Generous, not automatic overpay", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-027", title: "Set a weekly money date reminder", description: "Calendar the review", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-028", title: "Move idle cash to a high-yield option", description: "Idle is expensive", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-029", title: "Note emotional trigger before a buy", description: "Name it to tame it", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-030", title: "Use a cash envelope for one category", description: "Physical limit", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-wealth-031", title: "Check if an extended warranty is worth it", description: "Often skip", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-032", title: "Draft a listing for one unused item", description: "Turn clutter to cash", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-033", title: "Verify autopay dates", description: "Avoid late fees", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-034", title: "Read the fine print on one offer", description: "Gotchas live there", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-035", title: "Calculate your true hourly rate once", description: "Time is money", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-wealth-036", title: "Skip dessert when eating out", description: "Keep the social, cut the add-on", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-037", title: "Use the library instead of buying a book", description: "Free knowledge", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-038", title: "Check bank alert settings", description: "Early warning system", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-039", title: "Enable round-up savings if available", description: "Set and forget", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-040", title: "Review store orders this month", description: "Pattern hunt", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-wealth-041", title: "Avoid ATM fees today", description: "Use your network", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-042", title: "Put a windfall plan on paper", description: "Decide before dopamine", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-043", title: "Apply a coupon only after the list", description: "Stack, do not invent buys", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-044", title: "Track a side income idea in notes", description: "Plant the seed", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-045", title: "Review insurance deductible briefly", description: "Know your exposure", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-wealth-046", title: "Practice a walk without buying anything", description: "Browse is a tax", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-047", title: "Set calendar reminder for tax docs", description: "Future calm", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-048", title: "Compare phone plan options", description: "Silent monthly drain", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-049", title: "Pay one small bill early", description: "Zero drama", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-050", title: "Audit streaming services", description: "Keep what you watch", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-wealth-051", title: "Use cashback only on a planned buy", description: "Never invent a purchase", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-052", title: "Check retirement contribution percent", description: "Future paycheck", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-053", title: "Write financial goal in one sentence", description: "Clarity", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-054", title: "Skip a mall or big-box wander", description: "Defaults matter", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-055", title: "Review tips on last few receipts", description: "Pattern awareness", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-wealth-056", title: "Start a $1 daily savings challenge", description: "Proof of motion", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-057", title: "Check credit utilization", description: "Keep powder dry", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-058", title: "List debts with balances", description: "Face the dragon", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-059", title: "Celebrate a frugal win privately", description: "Reinforce the identity", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: true },
  { id: "cat-wealth-060", title: "Leave loyalty apps logged out today", description: "Reduce nudge noise", category: "wealth", difficulty: "easy", xpReward: 10, isDaily: false },
  { id: "cat-wealth-061", title: "Build or update a monthly budget", description: "Every dollar gets a job", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-062", title: "Negotiate one bill", description: "Ask once, save months", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-063", title: "Sell something you do not use", description: "Cash plus space", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-wealth-064", title: "Automate a savings transfer", description: "Remove willpower", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-065", title: "Review last 30 days of spending", description: "Find the leaks", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-066", title: "Pay extra on highest-interest debt", description: "Math-first attack", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-wealth-067", title: "Open or fund an emergency fund goal", description: "Starters if new", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-068", title: "Create a sinking fund for a known expense", description: "No holiday ambush", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-069", title: "Compare insurance quotes", description: "Loyalty can be expensive", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-wealth-070", title: "Set up a bill calendar for the month", description: "No surprise due dates", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-071", title: "Track net worth for this month", description: "Zoom out", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-072", title: "Cap dining out for the week", description: "Boundary with fun", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-wealth-073", title: "Research index fund basics", description: "Own the market patiently", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-074", title: "File or organize tax documents", description: "April becomes boring", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-075", title: "Use a 72-hour rule on a big purchase", description: "Wait, then decide", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-wealth-076", title: "Build a no-spend weekend plan", description: "Fun without the swipe", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-077", title: "Research refinancing numbers", description: "Run the math", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-078", title: "Update beneficiaries on accounts", description: "Adult paperwork", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-wealth-079", title: "Create debt snowball or avalanche plan", description: "Pick a method, commit", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-080", title: "Audit subscriptions with accountability", description: "Cancel what you ignore", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-081", title: "Separate bills vs spending accounts", description: "Buckets reduce chaos", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-wealth-082", title: "Calculate runway if income stopped", description: "Know your months", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-083", title: "Plan a side hustle first-dollar step", description: "Concrete next action", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-084", title: "Review investment fees", description: "Bps compound against you", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-wealth-085", title: "Build a holiday gift budget early", description: "December without debt", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-086", title: "Check credit report for errors", description: "Dispute what is wrong", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-087", title: "Automate minimum plus extra debt payment", description: "Systems over moods", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-wealth-088", title: "Cook from pantry and freezer this week", description: "Spend inventory first", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-089", title: "Hit a halfway checkpoint on a money goal", description: "Adjust if needed", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-090", title: "Research employer retirement match", description: "Free money if available", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-wealth-091", title: "Create an intentional giving budget", description: "Generosity with a plan", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-092", title: "Build a car maintenance sinking fund", description: "Repairs will not wreck you", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-093", title: "Ask about a medical bill payment plan", description: "Cash discount possible", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-wealth-094", title: "Update resume while reviewing income goals", description: "Career is a wealth lever", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-095", title: "Return or price-match an unused buy", description: "Reverse the leak", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-096", title: "Set category caps in your budget app", description: "Hard rails", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-wealth-097", title: "Do a cash-only day", description: "Feel the spend", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-098", title: "Review housing costs vs income", description: "Biggest lever", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-099", title: "Plan a quarterly money review date", description: "Zoom-out ritual", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-wealth-100", title: "Research HSA or FSA if eligible", description: "Tax-advantaged care", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-101", title: "List assets you could monetize", description: "Skills, stuff, space", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-102", title: "Cut one lifestyle-creep item", description: "Keep upgrades intentional", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-wealth-103", title: "Build a travel fund before booking", description: "Pay then play", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-104", title: "Read a chapter on investing basics", description: "Literacy", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-105", title: "Set up two-factor on financial accounts", description: "Security is wealth", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-wealth-106", title: "Forecast next 3 months cashflow", description: "See the squeeze early", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-107", title: "Prep a raise ask with a win list", description: "Evidence folder", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-108", title: "Compare bank fees and switch if needed", description: "Stop paying to hold money", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-wealth-109", title: "Create a fun-money envelope", description: "Guilt-free spending lane", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-110", title: "Review tax withholding", description: "Avoid April shock", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-111", title: "Batch cook to cut food waste", description: "Money in the trash otherwise", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-wealth-112", title: "Map a debt freedom date", description: "Motivation with math", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-113", title: "Start a structured savings challenge", description: "Gamify the stack", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-114", title: "Secure money logins in a password manager", description: "Ops hygiene", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: true },
  { id: "cat-wealth-115", title: "Start a 30-day wardrobe shop ban", description: "Wear what you own", category: "wealth", difficulty: "medium", xpReward: 25, isDaily: false },
  { id: "cat-wealth-116", title: "Write a full personal financial plan", description: "Goals, budget, debt, invest", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-117", title: "Reach a $100 savings milestone this month", description: "Floor raised", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-118", title: "Pay off a small debt entirely", description: "Close the account win", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-119", title: "Grow emergency fund toward 1 month expenses", description: "Real safety", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-120", title: "Complete a no-spend week", description: "Prove control", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-121", title: "Increase retirement contribution", description: "Future raise", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-122", title: "Negotiate salary or freelance rate", description: "Ask with evidence", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-123", title: "Write your own investing rules", description: "Rules beat vibes", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-124", title: "Start tax prep early with organized docs", description: "File without panic", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-125", title: "Build a dated 3-month emergency fund plan", description: "Concrete runway", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-126", title: "Cut a major housing or transport cost", description: "Big lever change", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-127", title: "Launch a monetized offer", description: "First invoice path", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-128", title: "Pay $500+ principal on debt this month", description: "Aggressive progress", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-129", title: "Build a net worth model with projections", description: "Spreadsheet clarity", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-130", title: "Cut a lifestyle that fights your goals", description: "Hard edit", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-131", title: "Finish a money course module and apply it", description: "Learn then do", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-132", title: "Refinance or consolidate with clear savings", description: "Paperwork win", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-133", title: "Keep a side-business P&L for 30 days", description: "Treat it real", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-134", title: "Review health, renters, and auto cover", description: "Transfer risk wisely", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-135", title: "Check will or beneficiary basics", description: "Protect people", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-136", title: "Hit a target savings rate this month", description: "Percent of income", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-137", title: "Sell $200+ of unused items", description: "Declutter dividend", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-138", title: "Automate your entire paycheck split", description: "Zero leftover chaos", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-139", title: "Talk with a fiduciary or nonprofit counselor", description: "Get help if needed", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-140", title: "Build a year-ahead major expense calendar", description: "No ambushes", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-141", title: "Complete a career move that raises income", description: "Wealth skill tree", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-142", title: "Stick to a strict budget for 14 days", description: "Track and hit", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-143", title: "Pay cash for a planned big purchase", description: "No financing trap", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-144", title: "Start a second income stream", description: "Resilience", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-145", title: "Write a 12-month credit improvement plan", description: "Roadmap", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-146", title: "Schedule automatic investment contributions", description: "Auto the boring", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-147", title: "Kick off a high-interest debt attack plan", description: "Attack APR", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-148", title: "Start an education or kids fund if relevant", description: "Long game", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-149", title: "Audit insurance docs for claim readiness", description: "Be prepared", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
  { id: "cat-wealth-150", title: "Sketch your financial independence number", description: "North star math", category: "wealth", difficulty: "hard", xpReward: 50, isDaily: false },
];
